
-- =============================================
-- AUTHOR: 郭凯斌
-- CREATE DATE: 2013-10-17
-- DESCRIPTION: 预算报账查询存储过程(有关联金碟K3数据库数据)
-- =============================================

Create Procedure P_Budget_Report(
@LS_CATEGORY VARCHAR(200),
@LS_NON_DETAIL VARCHAR(200),
@LI_USER_ID INT
)
AS
BEGIN

SET ANSI_NULLS ON
SET ANSI_WARNINGS ON

DECLARE @LS_SQL VARCHAR(8000)
DECLARE @LS_SERVER VARCHAR(200)
DECLARE @LS_USER VARCHAR(200)
DECLARE @LS_PASSWORD VARCHAR(200)
DECLARE @LS_DATABASE VARCHAR(200)
DECLARE @LS_USER_ID VARCHAR(200)

IF (NOT LEN(@LS_CATEGORY)>0) OR @LS_CATEGORY IS NULL OR (NOT @LS_CATEGORY IN ('预算报账','差旅费报账','差旅费报账_产品类别')) OR
(NOT LEN(@LS_NON_DETAIL)>0) OR @LS_NON_DETAIL IS NULL OR (NOT @LS_NON_DETAIL IN ('是','否')) OR
(NOT @LI_USER_ID>0) OR @LI_USER_ID IS NULL
RETURN

SET @LS_USER_ID=CAST(@LI_USER_ID AS VARCHAR(200))

SELECT @LS_SERVER=FVALUE FROM T_SYSPROFILE WITH(NOLOCK) WHERE FSUBSYS='SYS' AND FALIASNAME='KINGSOFTSERVER'

SELECT @LS_USER=FVALUE FROM T_SYSPROFILE WITH(NOLOCK) WHERE FSUBSYS='SYS' AND FALIASNAME='KINGSOFTDBUSER'

SELECT @LS_PASSWORD=FVALUE FROM T_SYSPROFILE WITH(NOLOCK) WHERE FSUBSYS='SYS' AND FALIASNAME='KINGSOFTDBPS'

SELECT @LS_DATABASE=FVALUE FROM T_SYSPROFILE WITH(NOLOCK) WHERE FSUBSYS='SYS' AND FALIASNAME='KINGSOFTDBNAME'

IF @LS_PASSWORD IS NULL
SET @LS_PASSWORD=''

IF (NOT LEN(@LS_SERVER)>0) OR @LS_SERVER IS NULL OR 
(NOT LEN(@LS_USER)>0) OR @LS_USER IS NULL OR
(NOT LEN(@LS_DATABASE)>0) OR @LS_DATABASE IS NULL
BEGIN
	IF @LS_CATEGORY='预算报账' AND @LS_NON_DETAIL='否'
	BEGIN
		
		SET @LS_SQL=
		'SELECT
		H.FID,
		H.FNO,
		H.FBUDGET_CENTER_ID,
		(SELECT C1.FNO FROM T_BUDGET_CENTER AS C1 WITH(NOLOCK) WHERE C1.FID=H.FBUDGET_CENTER_ID) AS FBUDGET_CENTER_NO,
		(SELECT C2.FNAME FROM T_BUDGET_CENTER AS C2 WITH(NOLOCK) WHERE C2.FID=H.FBUDGET_CENTER_ID) AS FBUDGET_CENTER_NAME,
		H.FDATE,
		H.FSTATE,
		H.FREMARK,
		H.FCREATE_ID,
		(SELECT U1.FNAME FROM T_USER AS U1 WITH(NOLOCK) WHERE U1.FINTERID=H.FCREATE_ID) AS FCREATE,
		H.FCREATE_DATE,
		H.FCONFIRM_ID,
		(SELECT U2.FNAME FROM T_USER AS U2 WITH(NOLOCK) WHERE U2.FINTERID=H.FCONFIRM_ID) AS FCONFIRM,
		H.FCONFIRM_DATE,
		H.FTALLY_ID,
		(SELECT U3.FNAME FROM T_USER AS U3 WITH(NOLOCK) WHERE U3.FINTERID=H.FTALLY_ID) AS FTALLY,
		H.FTALLY_DATE,
		H.FVOUCHER_ID,
		H.FLEVEL,
		CASE
		WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_VIEW AS P1 WITH(NOLOCK) WHERE P1.FCATEGORY=''预算报账'' AND P1.FBUDGET_CENTER_ID=H.FBUDGET_CENTER_ID AND P1.FUSER_ID='+@LS_USER_ID+') THEN 0
		ELSE 1
		END AS FPERMISSION_VIEW,
		CASE
		WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_CONFIRM AS P2 WITH(NOLOCK) WHERE P2.FCATEGORY=''预算报账'' AND P2.FBUDGET_CENTER_ID=H.FBUDGET_CENTER_ID AND P2.FLEVEL=H.FLEVEL+1 AND P2.FUSER_ID='+@LS_USER_ID+') AND H.FSTATE=1 THEN 0
		ELSE 1
		END AS FPERMISSION_CONFIRM,
		CASE
		WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_CONFIRM AS P3 WITH(NOLOCK) WHERE P3.FCATEGORY=''预算报账'' AND P3.FBUDGET_CENTER_ID=H.FBUDGET_CENTER_ID AND P3.FLEVEL=H.FLEVEL AND P3.FUSER_ID='+@LS_USER_ID+') AND H.FSTATE IN (1,2) AND H.FLEVEL>0 AND NOT H.FLEVEL IS NULL THEN 0
		ELSE 1
		END AS FPERMISSION_UN_CONFIRM,
		CASE
		WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P4 WITH(NOLOCK) WHERE P4.FFUNCTIONID=970030000 AND P4.FUSERID='+@LS_USER_ID+' AND P4.FRIGHT=2) THEN 0
		ELSE 1
		END AS FPERMISSION_EDIT,
		CASE
		WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P5 WITH(NOLOCK) WHERE P5.FFUNCTIONID=970030000 AND P5.FUSERID='+@LS_USER_ID+' AND P5.FRIGHT=2 AND P5.FMODIFYOTHER=1) THEN 0
		ELSE 1
		END AS FPERMISSION_EDIT_ALL,
		CASE
		WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P5 WITH(NOLOCK) WHERE P5.FFUNCTIONID=970030100 AND P5.FUSERID='+@LS_USER_ID+' AND NOT P5.FRIGHT=0) AND H.FSTATE=2 THEN 0
		ELSE 1
		END AS FPERMISSION_TALLY,
		CASE
		WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P6 WITH(NOLOCK) WHERE P6.FFUNCTIONID=970030100 AND P6.FUSERID='+@LS_USER_ID+' AND NOT P6.FRIGHT=0) AND H.FSTATE=3 THEN 0
		ELSE 1
		END AS FPERMISSION_UN_TALLY,
		CASE
		WHEN CONVERT(CHAR(10),H.FDATE,20)>=ISNULL((SELECT CONVERT(CHAR(10),MIN(O1.FBEGDATE),20) FROM T_ACCOUNTPERIOD AS O1 WITH(NOLOCK) WHERE O1.FYEAR=(SELECT MAX(O2.FYEAR) FROM T_ACCOUNTPERIOD AS O2 WITH(NOLOCK) WHERE O2.FSTATUS=1) AND O1.FSTATUS=1),'''')
		AND CONVERT(CHAR(10),H.FDATE,20)<=ISNULL((SELECT CONVERT(CHAR(10),MAX(O3.FENDDATE),20) FROM T_ACCOUNTPERIOD AS O3 WITH(NOLOCK) WHERE O3.FYEAR=(SELECT MAX(O4.FYEAR) FROM T_ACCOUNTPERIOD AS O4 WITH(NOLOCK) WHERE O4.FSTATUS=1) AND O3.FSTATUS=1),'''')
		THEN 0
		ELSE
		1
		END AS FFILTER_PERIOD,
		H.FVALUE_BUDGET_CENTER_ID,
		(SELECT C3.FNO FROM T_BUDGET_CENTER AS C3 WITH(NOLOCK) WHERE C3.FID=H.FVALUE_BUDGET_CENTER_ID) AS FVALUE_BUDGET_CENTER_NO,
		(SELECT C4.FNAME FROM T_BUDGET_CENTER AS C4 WITH(NOLOCK) WHERE C4.FID=H.FVALUE_BUDGET_CENTER_ID) AS FVALUE_BUDGET_CENTER_NAME,
		D.FROW,
		D.FBUDGET_ITEM_ID,
		(SELECT I1.FNO FROM T_BUDGET_ITEM AS I1 WITH(NOLOCK) WHERE I1.FID=D.FBUDGET_ITEM_ID) AS FBUDGET_ITEM_NO,
		(SELECT I2.FNAME FROM T_BUDGET_ITEM AS I2 WITH(NOLOCK) WHERE I2.FID=D.FBUDGET_ITEM_ID) AS FBUDGET_ITEM_NAME,
		(SELECT ASSITEM.FNAME FROM T_BUDGET_ASSISTANT_ITEM AS ASSITEM WITH(NOLOCK) WHERE ASSITEM.FID=D.FASSISTANT_ITEM_ID) AS FBUDGET_ASSISTANT_NAME,
		D.FAMOUNT,
		D.FCREDIT_ID,
		(SELECT A1.FACCOUNTNO FROM T_ACCOUNT AS A1 WITH(NOLOCK) WHERE A1.FACCID=D.FCREDIT_ID) AS FCREDIT_NO,
		(SELECT A2.FACCOUNTNAME FROM T_ACCOUNT AS A2 WITH(NOLOCK) WHERE A2.FACCID=D.FCREDIT_ID) AS FCREDIT_NAME,
		D.FDEBIT_ID,
		(SELECT A3.FACCOUNTNO FROM T_ACCOUNT AS A3 WITH(NOLOCK) WHERE A3.FACCID=D.FDEBIT_ID) AS FDEBIT_NO,
		(SELECT A4.FACCOUNTNAME FROM T_ACCOUNT AS A4 WITH(NOLOCK) WHERE A4.FACCID=D.FDEBIT_ID) AS FDEBIT_NAME,
		(SELECT C3.FPY FROM T_BUDGET_CENTER AS C3 WITH(NOLOCK) WHERE C3.FID=H.FBUDGET_CENTER_ID) AS FBUDGET_CNTER_PY,
		(SELECT I3.FPY FROM T_BUDGET_ITEM AS I3 WITH(NOLOCK) WHERE I3.FID=D.FBUDGET_ITEM_ID) AS FBUDGET_ITEM_PY,
		D.FPRODUCT_TYPE_ID,
		D.FPRODUCT_TYPE AS FDETAIL_PRODUCT_TYPE,
		CASE D.FPRODUCT_TYPE
		WHEN ''TOP'' THEN (SELECT T.FNAME FROM T_BATCHNO_PRODTYPE AS T WITH(NOLOCK) WHERE T.FID=D.FPRODUCT_TYPE_ID)
		WHEN ''CHILDREN'' THEN (SELECT C.FONENAME+'' - ''+C.FTWONAME FROM T_BATCHNO_CLASS AS C WITH(NOLOCK) WHERE C.FID=D.FPRODUCT_TYPE_ID)
		END AS FPRODUCT_TYPE_NAME,
		H.FCONFIRM_STATE,
		D.FREVISE,
		H.FPRODUCT_TYPE,
		(SELECT SUM(RD.FAMOUNT) FROM T_BUDGET_REPORT_DETAIL AS RD WITH(NOLOCK) WHERE RD.FID=H.FID) AS FAMOUNT_SUM,
		D.FSUMMARY,
		D.FEMPLOYEE_ID,
		(SELECT E1.FNO FROM T_EMP AS E1 WITH(NOLOCK) WHERE E1.FINTERID=D.FEMPLOYEE_ID) AS FEMPLOYEE_NO,
		(SELECT E2.FNAME FROM T_EMP AS E2 WITH(NOLOCK) WHERE E2.FINTERID=D.FEMPLOYEE_ID) AS FEMPLOYEE_NAME,
		H.FDEPARTMENT_ID,
		(SELECT D1.FCODE FROM T_DEPARTMENT AS D1 WITH(NOLOCK) WHERE D1.FINTERID=H.FDEPARTMENT_ID) AS FDEPARTMENT_NO,
		(SELECT D2.FDMNAME FROM T_DEPARTMENT AS D2 WITH(NOLOCK) WHERE D2.FINTERID=H.FDEPARTMENT_ID) AS FDEPARTMENT_NAME,
		H.FDEPARTMENT,
		'''' AS FKINGDEE_VOUCHER_CODE,
		H.FCHECK,
		D.FSELL_YEAR,
		H.FINHERIT_MANAGEMENT_MATERIAL
		FROM (
		SELECT
		RH.*,
		CASE
		WHEN EXISTS(
		SELECT
		1
		FROM TIC_INSTOCKITEMS QD WITH(NOLOCK)
		WHERE
		QD.FBUDGET_REPORT_ID=RH.FID
		) THEN ''是''
		ELSE ''否''
		END ''FINHERIT_MANAGEMENT_MATERIAL''
		FROM T_BUDGET_REPORT_HEADER RH WITH(NOLOCK)
		) H
		INNER JOIN T_BUDGET_REPORT_DETAIL AS D WITH(NOLOCK) ON D.FID=H.FID
		'
		
	END
	
	IF @LS_CATEGORY='预算报账' AND @LS_NON_DETAIL='是'
	BEGIN
		
		SET @LS_SQL=	
		'SELECT
		H.FID,
		H.FNO,
		H.FBUDGET_CENTER_ID,
		(SELECT C1.FNO FROM T_BUDGET_CENTER AS C1 WITH(NOLOCK) WHERE C1.FID=H.FBUDGET_CENTER_ID) AS FBUDGET_CENTER_NO,
		(SELECT C2.FNAME FROM T_BUDGET_CENTER AS C2 WITH(NOLOCK) WHERE C2.FID=H.FBUDGET_CENTER_ID) AS FBUDGET_CENTER_NAME,
		H.FDATE,
		H.FSTATE,
		H.FREMARK,
		H.FCREATE_ID,
		(SELECT U1.FNAME FROM T_USER AS U1 WITH(NOLOCK) WHERE U1.FINTERID=H.FCREATE_ID) AS FCREATE,
		H.FCREATE_DATE,
		H.FCONFIRM_ID,
		(SELECT U2.FNAME FROM T_USER AS U2 WITH(NOLOCK) WHERE U2.FINTERID=H.FCONFIRM_ID) AS FCONFIRM,
		H.FCONFIRM_DATE,
		H.FTALLY_ID,
		(SELECT U3.FNAME FROM T_USER AS U3 WITH(NOLOCK) WHERE U3.FINTERID=H.FTALLY_ID) AS FTALLY,
		H.FTALLY_DATE,
		H.FVOUCHER_ID,
		H.FLEVEL,
		CASE
		WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_VIEW AS P1 WITH(NOLOCK) WHERE P1.FCATEGORY=''预算报账'' AND P1.FBUDGET_CENTER_ID=H.FBUDGET_CENTER_ID AND P1.FUSER_ID='+@LS_USER_ID+') THEN 0
		ELSE 1
		END AS FPERMISSION_VIEW,
		CASE
		WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_CONFIRM AS P2 WITH(NOLOCK) WHERE P2.FCATEGORY=''预算报账'' AND P2.FBUDGET_CENTER_ID=H.FBUDGET_CENTER_ID AND P2.FLEVEL=H.FLEVEL+1 AND P2.FUSER_ID='+@LS_USER_ID+') AND H.FSTATE=1 THEN 0
		ELSE 1
		END AS FPERMISSION_CONFIRM,
		CASE
		WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_CONFIRM AS P3 WITH(NOLOCK) WHERE P3.FCATEGORY=''预算报账'' AND P3.FBUDGET_CENTER_ID=H.FBUDGET_CENTER_ID AND P3.FLEVEL=H.FLEVEL AND P3.FUSER_ID='+@LS_USER_ID+') AND H.FSTATE IN (1,2) AND H.FLEVEL>0 AND NOT H.FLEVEL IS NULL THEN 0
		ELSE 1
		END AS FPERMISSION_UN_CONFIRM,
		CASE
		WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P4 WITH(NOLOCK) WHERE P4.FFUNCTIONID=970030000 AND P4.FUSERID='+@LS_USER_ID+' AND P4.FRIGHT=2) THEN 0
		ELSE 1
		END AS FPERMISSION_EDIT,
		CASE
		WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P5 WITH(NOLOCK) WHERE P5.FFUNCTIONID=970030000 AND P5.FUSERID='+@LS_USER_ID+' AND P5.FRIGHT=2 AND P5.FMODIFYOTHER=1) THEN 0
		ELSE 1
		END AS FPERMISSION_EDIT_ALL,
		CASE
		WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P5 WITH(NOLOCK) WHERE P5.FFUNCTIONID=970030100 AND P5.FUSERID='+@LS_USER_ID+' AND NOT P5.FRIGHT=0) AND H.FSTATE=2 THEN 0
		ELSE 1
		END AS FPERMISSION_TALLY,
		CASE
		WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P6 WITH(NOLOCK) WHERE P6.FFUNCTIONID=970030100 AND P6.FUSERID='+@LS_USER_ID+' AND NOT P6.FRIGHT=0) AND H.FSTATE=3 THEN 0
		ELSE 1
		END AS FPERMISSION_UN_TALLY,
		CASE
		WHEN CONVERT(CHAR(10),H.FDATE,20)>=ISNULL((SELECT CONVERT(CHAR(10),MIN(O1.FBEGDATE),20) FROM T_ACCOUNTPERIOD AS O1 WITH(NOLOCK) WHERE O1.FYEAR=(SELECT MAX(O2.FYEAR) FROM T_ACCOUNTPERIOD AS O2 WITH(NOLOCK) WHERE O2.FSTATUS=1) AND O1.FSTATUS=1),'''')
		AND CONVERT(CHAR(10),H.FDATE,20)<=ISNULL((SELECT CONVERT(CHAR(10),MAX(O3.FENDDATE),20) FROM T_ACCOUNTPERIOD AS O3 WITH(NOLOCK) WHERE O3.FYEAR=(SELECT MAX(O4.FYEAR) FROM T_ACCOUNTPERIOD AS O4 WITH(NOLOCK) WHERE O4.FSTATUS=1) AND O3.FSTATUS=1),'''')
		THEN 0
		ELSE
		1
		END AS FFILTER_PERIOD,
		H.FVALUE_BUDGET_CENTER_ID,
		(SELECT C3.FNO FROM T_BUDGET_CENTER AS C3 WITH(NOLOCK) WHERE C3.FID=H.FVALUE_BUDGET_CENTER_ID) AS FVALUE_BUDGET_CENTER_NO,
		(SELECT C4.FNAME FROM T_BUDGET_CENTER AS C4 WITH(NOLOCK) WHERE C4.FID=H.FVALUE_BUDGET_CENTER_ID) AS FVALUE_BUDGET_CENTER_NAME,
		(SELECT C3.FPY FROM T_BUDGET_CENTER AS C3 WITH(NOLOCK) WHERE C3.FID=H.FBUDGET_CENTER_ID) AS FBUDGET_CNTER_PY,
		H.FCONFIRM_STATE,
		H.FPRODUCT_TYPE,
		(SELECT SUM(RD.FAMOUNT) FROM T_BUDGET_REPORT_DETAIL AS RD WITH(NOLOCK) WHERE RD.FID=H.FID) AS FAMOUNT_SUM,
		H.FDEPARTMENT_ID,
		(SELECT D1.FCODE FROM T_DEPARTMENT AS D1 WITH(NOLOCK) WHERE D1.FINTERID=H.FDEPARTMENT_ID) AS FDEPARTMENT_NO,
		(SELECT D2.FDMNAME FROM T_DEPARTMENT AS D2 WITH(NOLOCK) WHERE D2.FINTERID=H.FDEPARTMENT_ID) AS FDEPARTMENT_NAME,
		H.FDEPARTMENT,
		'''' AS FKINGDEE_VOUCHER_CODE,
		H.FCHECK,
		H.FINHERIT_MANAGEMENT_MATERIAL
		FROM (
		SELECT
		RH.*,
		CASE
		WHEN EXISTS(
		SELECT
		1
		FROM TIC_INSTOCKITEMS QD WITH(NOLOCK)
		WHERE
		QD.FBUDGET_REPORT_ID=RH.FID
		) THEN ''是''
		ELSE ''否''
		END ''FINHERIT_MANAGEMENT_MATERIAL''
		FROM T_BUDGET_REPORT_HEADER RH WITH(NOLOCK)
		) H
		'
		
	END
	
	IF @LS_CATEGORY='差旅费报账' AND @LS_NON_DETAIL='否'
	BEGIN
		
		SET @LS_SQL=
		'SELECT
		B.FID,
		B.FNO,
		B.FSTATE,
		B.FDEPARTMENTID,
		(SELECT ''(''+P.FCODE+'')''+P.FDMNAME FROM T_DEPARTMENT AS P WITH(NOLOCK) WHERE P.FINTERID=B.FDEPARTMENTID) AS FDEPARTMENT,
		B.FEMPID,
		(SELECT ''(''+E.FNO+'')''+E.FNAME FROM T_EMP AS E WITH(NOLOCK) WHERE E.FINTERID=B.FEMPID) AS FEMP,
		B.FCONTENT,
		B.FDATE,
		B.FUSERID,
		(SELECT U1.FNAME FROM T_USER AS U1 WITH(NOLOCK) WHERE U1.FINTERID=B.FUSERID) AS FUSER,
		(SELECT SUM(D.FAMOUNT) FROM T_BT_D AS D WITH(NOLOCK) WHERE D.FID=B.FID) AS FAMOUNT,
		B.FLEVEL,
		B.FBUDGETCENTERID,
		(SELECT C.FNO FROM T_BUDGET_CENTER AS C WITH(NOLOCK) WHERE C.FID=B.FBUDGETCENTERID) AS FBUDGET_CENTER_NO,
		B.FBUDGETITEMID,
		(SELECT I.FNO FROM T_BUDGET_ITEM AS I WITH(NOLOCK) WHERE I.FID=B.FBUDGETITEMID) AS FBUDGET_ITEM_NO,
		B.FPERIOD,
		B.FDEBIT_ID AS FACCOUNTID,
		(SELECT ''(''+A1.FACCOUNTNO+'')''+A1.FACCOUNTNAME FROM T_ACCOUNT AS A1 WITH(NOLOCK) WHERE A1.FACCID=B.FDEBIT_ID) AS FACCOUNT,
		B.FACCDOCID,
		B.FCREDITACCID,
		(SELECT ''(''+A1.FACCOUNTNO+'')''+A1.FACCOUNTNAME FROM T_ACCOUNT AS A1 WITH(NOLOCK) WHERE A1.FACCID=B.FCREDITACCID) AS FCREDITACC,
		(SELECT D1.FDOCNO FROM T_FI_ACCDOC AS D1 WITH(NOLOCK) WHERE D1.FACCTDOCID=B.FACCDOCID) AS FACCDOC,
		CASE
		WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_VIEW AS P1 WITH(NOLOCK) WHERE P1.FCATEGORY=''差旅费报账'' AND P1.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND P1.FUSER_ID='+@LS_USER_ID+') THEN 0
		ELSE 1
		END AS FPERMISSION_VIEW,
		CASE
		WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_CONFIRM AS P2 WITH(NOLOCK) WHERE P2.FCATEGORY=''差旅费报账'' AND P2.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND P2.FLEVEL=B.FLEVEL+1 AND P2.FUSER_ID='+@LS_USER_ID+') AND B.FSTATE=1 THEN 0
		ELSE 1
		END AS FPERMISSION_CONFIRM,
		CASE
		WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_CONFIRM AS P3 WITH(NOLOCK) WHERE P3.FCATEGORY=''差旅费报账'' AND P3.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND P3.FLEVEL=B.FLEVEL AND P3.FUSER_ID='+@LS_USER_ID+') AND B.FSTATE IN (1,2) AND B.FLEVEL>0 AND NOT B.FLEVEL IS NULL THEN 0
		ELSE 1
		END AS FPERMISSION_UN_CONFIRM,
		CASE
		WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P4 WITH(NOLOCK) WHERE P4.FFUNCTIONID=970030200 AND P4.FUSERID='+@LS_USER_ID+' AND P4.FRIGHT=2) THEN 0
		ELSE 1
		END AS FPERMISSION_EDIT,
		CASE
		WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P5 WITH(NOLOCK) WHERE P5.FFUNCTIONID=970030200 AND P5.FUSERID='+@LS_USER_ID+' AND P5.FRIGHT=2 AND P5.FMODIFYOTHER=1) THEN 0
		ELSE 1
		END AS FPERMISSION_EDIT_ALL,
		CASE
		WHEN CONVERT(CHAR(10),B.FPERIOD,20)>=ISNULL((SELECT CONVERT(CHAR(10),MIN(O1.FBEGDATE),20) FROM T_ACCOUNTPERIOD AS O1 WITH(NOLOCK) WHERE O1.FYEAR=(SELECT MAX(O2.FYEAR) FROM T_ACCOUNTPERIOD AS O2 WITH(NOLOCK) WHERE O2.FSTATUS=1) AND O1.FSTATUS=1),'''')
		AND CONVERT(CHAR(10),B.FPERIOD,20)<=ISNULL((SELECT CONVERT(CHAR(10),MAX(O3.FENDDATE),20) FROM T_ACCOUNTPERIOD AS O3 WITH(NOLOCK) WHERE O3.FYEAR=(SELECT MAX(O4.FYEAR) FROM T_ACCOUNTPERIOD AS O4 WITH(NOLOCK) WHERE O4.FSTATUS=1) AND O3.FSTATUS=1),'''')
		THEN 0
		ELSE
		1
		END AS FFILTER_PERIOD,
		B.FVALUE_BUDGET_CENTER_ID,
		(SELECT C3.FNO FROM T_BUDGET_CENTER AS C3 WITH(NOLOCK) WHERE C3.FID=B.FVALUE_BUDGET_CENTER_ID) AS FVALUE_BUDGET_CENTER_NO,
		(SELECT C4.FNAME FROM T_BUDGET_CENTER AS C4 WITH(NOLOCK) WHERE C4.FID=B.FVALUE_BUDGET_CENTER_ID) AS FVALUE_BUDGET_CENTER_NAME,
		CASE
		WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P5 WITH(NOLOCK) WHERE P5.FFUNCTIONID=970030100 AND P5.FUSERID='+@LS_USER_ID+' AND NOT P5.FRIGHT=0) AND B.FSTATE=2 THEN 0
		ELSE 1
		END AS FPERMISSION_TALLY,
		CASE
		WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P6 WITH(NOLOCK) WHERE P6.FFUNCTIONID=970030100 AND P6.FUSERID='+@LS_USER_ID+' AND NOT P6.FRIGHT=0) AND B.FSTATE=3 THEN 0
		ELSE 1
		END AS FPERMISSION_UN_TALLY,
		B.FCONFIRM_ID,
		(SELECT U2.FNAME FROM T_USER AS U2 WITH(NOLOCK) WHERE U2.FINTERID=B.FCONFIRM_ID) AS FCONFIRM,
		B.FCONFIRM_DATE,
		B.FTALLY_ID,
		(SELECT U3.FNAME FROM T_USER AS U3 WITH(NOLOCK) WHERE U3.FINTERID=B.FTALLY_ID) AS FTALLY,
		B.FTALLY_DATE,
		D.FITEMID,
		(SELECT I.FNAME FROM T_BT_I AS I WITH(NOLOCK) WHERE I.FID=D.FITEMID) AS FITEM,
		D.FCONTENT AS FCONTENT_DETAIL,
		D.FCONTENT2 AS FCONTENT2_DETAIL,
		D.FAMOUNT AS FDETAIL_AMOUNT,
		D.FNO AS FNO_DETAIL,
		D.FREMARK AS FREMARK_DETAIL,
		(SELECT C3.FPY FROM T_BUDGET_CENTER AS C3 WITH(NOLOCK) WHERE C3.FID=B.FBUDGETCENTERID) AS FBUDGET_CNTER_PY,
		(SELECT I3.FPY FROM T_BUDGET_ITEM AS I3 WITH(NOLOCK) WHERE I3.FID=B.FBUDGETITEMID) AS FBUDGET_ITEM_PY,
		B.FCONFIRM_STATE,
		D.FSTANDARD AS FDETAIL_STANDARD,
		D.FAPPLY AS FDETAIL_APPLY,
		B.FPRODUCT_TYPE,
		(SELECT C.FNAME FROM T_BUDGET_CENTER AS C WITH(NOLOCK) WHERE C.FID=B.FBUDGETCENTERID) AS FBUDGET_CENTER_NAME,
		(SELECT I.FNAME FROM T_BUDGET_ITEM AS I WITH(NOLOCK) WHERE I.FID=B.FBUDGETITEMID) AS FBUDGET_ITEM_NAME,
		(SELECT ASSITEM.FNAME FROM T_BUDGET_ASSISTANT_ITEM AS ASSITEM WITH(NOLOCK) WHERE ASSITEM.FID=B.FASSISTANT_ITEM_ID) AS FBUDGET_ASSISTANT_NAME,
		'''' AS FKINGDEE_VOUCHER_CODE,
		B.FCHECK
		FROM T_BT AS B WITH(NOLOCK)
		INNER JOIN T_BT_D AS D WITH(NOLOCK) ON D.FID=B.FID
		'
		
	END	
		
	IF @LS_CATEGORY='差旅费报账' AND @LS_NON_DETAIL='是'
	BEGIN
		
		SET @LS_SQL=
		'SELECT
		B.FID,
		B.FNO,
		B.FSTATE,
		B.FDEPARTMENTID,
		(SELECT ''(''+P.FCODE+'')''+P.FDMNAME FROM T_DEPARTMENT AS P WITH(NOLOCK) WHERE P.FINTERID=B.FDEPARTMENTID) AS FDEPARTMENT,
		B.FEMPID,
		(SELECT ''(''+E.FNO+'')''+E.FNAME FROM T_EMP AS E WITH(NOLOCK) WHERE E.FINTERID=B.FEMPID) AS FEMP,
		B.FCONTENT,
		B.FDATE,
		B.FUSERID,
		(SELECT U1.FNAME FROM T_USER AS U1 WITH(NOLOCK) WHERE U1.FINTERID=B.FUSERID) AS FUSER,
		(SELECT SUM(D.FAMOUNT) FROM T_BT_D AS D WITH(NOLOCK) WHERE D.FID=B.FID) AS FAMOUNT,
		B.FLEVEL,
		B.FBUDGETCENTERID,
		(SELECT C.FNO FROM T_BUDGET_CENTER AS C WITH(NOLOCK) WHERE C.FID=B.FBUDGETCENTERID) AS FBUDGET_CENTER_NO,
		B.FBUDGETITEMID,
		(SELECT I.FNO FROM T_BUDGET_ITEM AS I WITH(NOLOCK) WHERE I.FID=B.FBUDGETITEMID) AS FBUDGET_ITEM_NO,
		B.FPERIOD,
		(SELECT IC1.FDEBIT_ID FROM T_BUDGET_CENTER_ITEM AS IC1 WITH(NOLOCK) WHERE IC1.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND IC1.FBUDGET_ITEM_ID=B.FBUDGETITEMID) AS FACCOUNTID,
		(SELECT (SELECT ''(''+A1.FACCOUNTNO+'')''+A1.FACCOUNTNAME FROM T_ACCOUNT AS A1 WITH(NOLOCK) WHERE A1.FACCID=IC2.FDEBIT_ID) FROM T_BUDGET_CENTER_ITEM AS IC2 WITH(NOLOCK) WHERE IC2.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND IC2.FBUDGET_ITEM_ID=B.FBUDGETITEMID) AS FACCOUNT,
		B.FACCDOCID,
		B.FCREDITACCID,
		(SELECT ''(''+A1.FACCOUNTNO+'')''+A1.FACCOUNTNAME FROM T_ACCOUNT AS A1 WITH(NOLOCK) WHERE A1.FACCID=B.FCREDITACCID) AS FCREDITACC,
		(SELECT D1.FDOCNO FROM T_FI_ACCDOC AS D1 WITH(NOLOCK) WHERE D1.FACCTDOCID=B.FACCDOCID) AS FACCDOC,
		CASE
		WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_VIEW AS P1 WITH(NOLOCK) WHERE P1.FCATEGORY=''差旅费报账'' AND P1.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND P1.FUSER_ID='+@LS_USER_ID+') THEN 0
		ELSE 1
		END AS FPERMISSION_VIEW,
		CASE
		WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_CONFIRM AS P2 WITH(NOLOCK) WHERE P2.FCATEGORY=''差旅费报账'' AND P2.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND P2.FLEVEL=B.FLEVEL+1 AND P2.FUSER_ID='+@LS_USER_ID+') AND B.FSTATE=1 THEN 0
		ELSE 1
		END AS FPERMISSION_CONFIRM,
		CASE
		WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_CONFIRM AS P3 WITH(NOLOCK) WHERE P3.FCATEGORY=''差旅费报账'' AND P3.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND P3.FLEVEL=B.FLEVEL AND P3.FUSER_ID='+@LS_USER_ID+') AND B.FSTATE IN (1,2) AND B.FLEVEL>0 AND NOT B.FLEVEL IS NULL THEN 0
		ELSE 1
		END AS FPERMISSION_UN_CONFIRM,
		CASE
		WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P4 WITH(NOLOCK) WHERE P4.FFUNCTIONID=970030200 AND P4.FUSERID='+@LS_USER_ID+' AND P4.FRIGHT=2) THEN 0
		ELSE 1
		END AS FPERMISSION_EDIT,
		CASE
		WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P5 WITH(NOLOCK) WHERE P5.FFUNCTIONID=970030200 AND P5.FUSERID='+@LS_USER_ID+' AND P5.FRIGHT=2 AND P5.FMODIFYOTHER=1) THEN 0
		ELSE 1
		END AS FPERMISSION_EDIT_ALL,
		CASE
		WHEN CONVERT(CHAR(10),B.FPERIOD,20)>=ISNULL((SELECT CONVERT(CHAR(10),MIN(O1.FBEGDATE),20) FROM T_ACCOUNTPERIOD AS O1 WITH(NOLOCK) WHERE O1.FYEAR=(SELECT MAX(O2.FYEAR) FROM T_ACCOUNTPERIOD AS O2 WITH(NOLOCK) WHERE O2.FSTATUS=1) AND O1.FSTATUS=1),'''')
		AND CONVERT(CHAR(10),B.FPERIOD,20)<=ISNULL((SELECT CONVERT(CHAR(10),MAX(O3.FENDDATE),20) FROM T_ACCOUNTPERIOD AS O3 WITH(NOLOCK) WHERE O3.FYEAR=(SELECT MAX(O4.FYEAR) FROM T_ACCOUNTPERIOD AS O4 WITH(NOLOCK) WHERE O4.FSTATUS=1) AND O3.FSTATUS=1),'''')
		THEN 0
		ELSE
		1
		END AS FFILTER_PERIOD,
		B.FVALUE_BUDGET_CENTER_ID,
		(SELECT C3.FNO FROM T_BUDGET_CENTER AS C3 WITH(NOLOCK) WHERE C3.FID=B.FVALUE_BUDGET_CENTER_ID) AS FVALUE_BUDGET_CENTER_NO,
		(SELECT C4.FNAME FROM T_BUDGET_CENTER AS C4 WITH(NOLOCK) WHERE C4.FID=B.FVALUE_BUDGET_CENTER_ID) AS FVALUE_BUDGET_CENTER_NAME,
		CASE
		WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P5 WITH(NOLOCK) WHERE P5.FFUNCTIONID=970030100 AND P5.FUSERID='+@LS_USER_ID+' AND NOT P5.FRIGHT=0) AND B.FSTATE=2 THEN 0
		ELSE 1
		END AS FPERMISSION_TALLY,
		CASE
		WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P6 WITH(NOLOCK) WHERE P6.FFUNCTIONID=970030100 AND P6.FUSERID='+@LS_USER_ID+' AND NOT P6.FRIGHT=0) AND B.FSTATE=3 THEN 0
		ELSE 1
		END AS FPERMISSION_UN_TALLY,
		B.FCONFIRM_ID,
		(SELECT U2.FNAME FROM T_USER AS U2 WITH(NOLOCK) WHERE U2.FINTERID=B.FCONFIRM_ID) AS FCONFIRM,
		B.FCONFIRM_DATE,
		B.FTALLY_ID,
		(SELECT U3.FNAME FROM T_USER AS U3 WITH(NOLOCK) WHERE U3.FINTERID=B.FTALLY_ID) AS FTALLY,
		B.FTALLY_DATE,
		(SELECT C3.FPY FROM T_BUDGET_CENTER AS C3 WITH(NOLOCK) WHERE C3.FID=B.FBUDGETCENTERID) AS FBUDGET_CNTER_PY,
		(SELECT I3.FPY FROM T_BUDGET_ITEM AS I3 WITH(NOLOCK) WHERE I3.FID=B.FBUDGETITEMID) AS FBUDGET_ITEM_PY,
		B.FCONFIRM_STATE,
		B.FPRODUCT_TYPE,
		(SELECT C.FNAME FROM T_BUDGET_CENTER AS C WITH(NOLOCK) WHERE C.FID=B.FBUDGETCENTERID) AS FBUDGET_CENTER_NAME,
		(SELECT I.FNAME FROM T_BUDGET_ITEM AS I WITH(NOLOCK) WHERE I.FID=B.FBUDGETITEMID) AS FBUDGET_ITEM_NAME,
		(SELECT ASSITEM.FNAME FROM T_BUDGET_ASSISTANT_ITEM AS ASSITEM WITH(NOLOCK) WHERE ASSITEM.FID=B.FASSISTANT_ITEM_ID) AS FBUDGET_ASSISTANT_NAME,
		'''' AS FKINGDEE_VOUCHER_CODE,
		B.FCHECK
		FROM T_BT AS B WITH(NOLOCK)
		'
		
	END
	
	IF @LS_CATEGORY='差旅费报账_产品类别'
	BEGIN
		
		SET @LS_SQL=
		'SELECT
		B.FID,
		B.FNO,
		B.FSTATE,
		B.FDEPARTMENTID,
		(SELECT ''(''+P.FCODE+'')''+P.FDMNAME FROM T_DEPARTMENT AS P WITH(NOLOCK) WHERE P.FINTERID=B.FDEPARTMENTID) AS FDEPARTMENT,
		B.FEMPID,
		(SELECT ''(''+E.FNO+'')''+E.FNAME FROM T_EMP AS E WITH(NOLOCK) WHERE E.FINTERID=B.FEMPID) AS FEMP,
		B.FCONTENT,
		B.FDATE,
		B.FUSERID,
		(SELECT U1.FNAME FROM T_USER AS U1 WITH(NOLOCK) WHERE U1.FINTERID=B.FUSERID) AS FUSER,
		(SELECT SUM(D.FAMOUNT) FROM T_BT_D AS D WITH(NOLOCK) WHERE D.FID=B.FID) AS FAMOUNT,
		B.FLEVEL,
		B.FBUDGETCENTERID,
		(SELECT C.FNO FROM T_BUDGET_CENTER AS C WITH(NOLOCK) WHERE C.FID=B.FBUDGETCENTERID) AS FBUDGET_CENTER_NO,
		B.FBUDGETITEMID,
		(SELECT I.FNO FROM T_BUDGET_ITEM AS I WITH(NOLOCK) WHERE I.FID=B.FBUDGETITEMID) AS FBUDGET_ITEM_NO,
		B.FPERIOD,
		B.FDEBIT_ID AS FACCOUNTID,
		(SELECT ''(''+A1.FACCOUNTNO+'')''+A1.FACCOUNTNAME FROM T_ACCOUNT AS A1 WITH(NOLOCK) WHERE A1.FACCID=B.FDEBIT_ID) AS FACCOUNT,
		B.FACCDOCID,
		B.FCREDITACCID,
		(SELECT ''(''+A1.FACCOUNTNO+'')''+A1.FACCOUNTNAME FROM T_ACCOUNT AS A1 WITH(NOLOCK) WHERE A1.FACCID=B.FCREDITACCID) AS FCREDITACC,
		(SELECT D1.FDOCNO FROM T_FI_ACCDOC AS D1 WITH(NOLOCK) WHERE D1.FACCTDOCID=B.FACCDOCID) AS FACCDOC,
		CASE
		WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_VIEW AS P1 WITH(NOLOCK) WHERE P1.FCATEGORY=''差旅费报账'' AND P1.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND P1.FUSER_ID='+@LS_USER_ID+') THEN 0
		ELSE 1
		END AS FPERMISSION_VIEW,
		CASE
		WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_CONFIRM AS P2 WITH(NOLOCK) WHERE P2.FCATEGORY=''差旅费报账'' AND P2.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND P2.FLEVEL=B.FLEVEL+1 AND P2.FUSER_ID='+@LS_USER_ID+') AND B.FSTATE=1 THEN 0
		ELSE 1
		END AS FPERMISSION_CONFIRM,
		CASE
		WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_CONFIRM AS P3 WITH(NOLOCK) WHERE P3.FCATEGORY=''差旅费报账'' AND P3.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND P3.FLEVEL=B.FLEVEL AND P3.FUSER_ID='+@LS_USER_ID+') AND B.FSTATE IN (1,2) AND B.FLEVEL>0 AND NOT B.FLEVEL IS NULL THEN 0
		ELSE 1
		END AS FPERMISSION_UN_CONFIRM,
		CASE
		WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P4 WITH(NOLOCK) WHERE P4.FFUNCTIONID=970030200 AND P4.FUSERID='+@LS_USER_ID+' AND P4.FRIGHT=2) THEN 0
		ELSE 1
		END AS FPERMISSION_EDIT,
		CASE
		WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P5 WITH(NOLOCK) WHERE P5.FFUNCTIONID=970030200 AND P5.FUSERID='+@LS_USER_ID+' AND P5.FRIGHT=2 AND P5.FMODIFYOTHER=1) THEN 0
		ELSE 1
		END AS FPERMISSION_EDIT_ALL,
		CASE
		WHEN CONVERT(CHAR(10),B.FPERIOD,20)>=ISNULL((SELECT CONVERT(CHAR(10),MIN(O1.FBEGDATE),20) FROM T_ACCOUNTPERIOD AS O1 WITH(NOLOCK) WHERE O1.FYEAR=(SELECT MAX(O2.FYEAR) FROM T_ACCOUNTPERIOD AS O2 WITH(NOLOCK) WHERE O2.FSTATUS=1) AND O1.FSTATUS=1),'''')
		AND CONVERT(CHAR(10),B.FPERIOD,20)<=ISNULL((SELECT CONVERT(CHAR(10),MAX(O3.FENDDATE),20) FROM T_ACCOUNTPERIOD AS O3 WITH(NOLOCK) WHERE O3.FYEAR=(SELECT MAX(O4.FYEAR) FROM T_ACCOUNTPERIOD AS O4 WITH(NOLOCK) WHERE O4.FSTATUS=1) AND O3.FSTATUS=1),'''')
		THEN 0
		ELSE
		1
		END AS FFILTER_PERIOD,
		B.FVALUE_BUDGET_CENTER_ID,
		(SELECT C3.FNO FROM T_BUDGET_CENTER AS C3 WITH(NOLOCK) WHERE C3.FID=B.FVALUE_BUDGET_CENTER_ID) AS FVALUE_BUDGET_CENTER_NO,
		(SELECT C4.FNAME FROM T_BUDGET_CENTER AS C4 WITH(NOLOCK) WHERE C4.FID=B.FVALUE_BUDGET_CENTER_ID) AS FVALUE_BUDGET_CENTER_NAME,
		CASE
		WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P5 WITH(NOLOCK) WHERE P5.FFUNCTIONID=970030100 AND P5.FUSERID='+@LS_USER_ID+' AND NOT P5.FRIGHT=0) AND B.FSTATE=2 THEN 0
		ELSE 1
		END AS FPERMISSION_TALLY,
		CASE
		WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P6 WITH(NOLOCK) WHERE P6.FFUNCTIONID=970030100 AND P6.FUSERID='+@LS_USER_ID+' AND NOT P6.FRIGHT=0) AND B.FSTATE=3 THEN 0
		ELSE 1
		END AS FPERMISSION_UN_TALLY,
		B.FCONFIRM_ID,
		(SELECT U2.FNAME FROM T_USER AS U2 WITH(NOLOCK) WHERE U2.FINTERID=B.FCONFIRM_ID) AS FCONFIRM,
		B.FCONFIRM_DATE,
		B.FTALLY_ID,
		(SELECT U3.FNAME FROM T_USER AS U3 WITH(NOLOCK) WHERE U3.FINTERID=B.FTALLY_ID) AS FTALLY,
		B.FTALLY_DATE,
		(SELECT C3.FPY FROM T_BUDGET_CENTER AS C3 WITH(NOLOCK) WHERE C3.FID=B.FBUDGETCENTERID) AS FBUDGET_CNTER_PY,
		(SELECT I3.FPY FROM T_BUDGET_ITEM AS I3 WITH(NOLOCK) WHERE I3.FID=B.FBUDGETITEMID) AS FBUDGET_ITEM_PY,
		B.FCONFIRM_STATE,
		B.FPRODUCT_TYPE,
		(SELECT C.FNAME FROM T_BUDGET_CENTER AS C WITH(NOLOCK) WHERE C.FID=B.FBUDGETCENTERID) AS FBUDGET_CENTER_NAME,
		(SELECT I.FNAME FROM T_BUDGET_ITEM AS I WITH(NOLOCK) WHERE I.FID=B.FBUDGETITEMID) AS FBUDGET_ITEM_NAME,
(SELECT ASSITEM.FNAME FROM T_BUDGET_ASSISTANT_ITEM AS ASSITEM WITH(NOLOCK) WHERE ASSITEM.FID=B.FASSISTANT_ITEM_ID) AS FBUDGET_ASSISTANT_NAME,
		'''' AS FKINGDEE_VOUCHER_CODE,
		B.FCHECK,
		P.FROW,
		P.FPRODUCT_TYPE AS FPRODUCT_TYPE_TOP,
		P.FPRODUCT_TYPE_ID,
		CASE P.FPRODUCT_TYPE
		WHEN ''TOP'' THEN (SELECT T.FNAME FROM T_BATCHNO_PRODTYPE AS T WITH(NOLOCK) WHERE T.FID=P.FPRODUCT_TYPE_ID)
		WHEN ''CHILDREN'' THEN (SELECT C.FONENAME+'' - ''+C.FTWONAME FROM T_BATCHNO_CLASS AS C WITH(NOLOCK) WHERE C.FID=P.FPRODUCT_TYPE_ID)
		END AS FPRODUCT_TYPE_NAME,
		P.FRATE,
		P.FMATERIAL_ID,
		(SELECT M1.FMATERIALNO FROM T_MATERIAL AS M1 WITH(NOLOCK) WHERE M1.FMATERIALID=P.FMATERIAL_ID) AS FMATERIAL_NO,
		(SELECT M2.FMATERIALNAME FROM T_MATERIAL AS M2 WITH(NOLOCK) WHERE M2.FMATERIALID=P.FMATERIAL_ID) AS FMATERIAL_NAME,
		P.FSELL_YEAR
		FROM T_BT AS B WITH(NOLOCK)
		INNER JOIN T_BT_P AS P WITH(NOLOCK) ON P.FID=B.FID
		'
		
	END

	EXEC(@LS_SQL)
	
	RETURN
END


IF @LS_CATEGORY='预算报账' AND @LS_NON_DETAIL='否'
BEGIN
	
	SET @LS_SQL=
	'SELECT
	H.FID,
	H.FNO,
	H.FBUDGET_CENTER_ID,
	(SELECT C1.FNO FROM T_BUDGET_CENTER AS C1 WITH(NOLOCK) WHERE C1.FID=H.FBUDGET_CENTER_ID) AS FBUDGET_CENTER_NO,
	(SELECT C2.FNAME FROM T_BUDGET_CENTER AS C2 WITH(NOLOCK) WHERE C2.FID=H.FBUDGET_CENTER_ID) AS FBUDGET_CENTER_NAME,
	H.FDATE,
	H.FSTATE,
	H.FREMARK,
	H.FCREATE_ID,
	(SELECT U1.FNAME FROM T_USER AS U1 WITH(NOLOCK) WHERE U1.FINTERID=H.FCREATE_ID) AS FCREATE,
	H.FCREATE_DATE,
	H.FCONFIRM_ID,
	(SELECT U2.FNAME FROM T_USER AS U2 WITH(NOLOCK) WHERE U2.FINTERID=H.FCONFIRM_ID) AS FCONFIRM,
	H.FCONFIRM_DATE,
	H.FTALLY_ID,
	(SELECT U3.FNAME FROM T_USER AS U3 WITH(NOLOCK) WHERE U3.FINTERID=H.FTALLY_ID) AS FTALLY,
	H.FTALLY_DATE,
	H.FVOUCHER_ID,
	H.FLEVEL,
	CASE
	WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_VIEW AS P1 WITH(NOLOCK) WHERE P1.FCATEGORY=''预算报账'' AND P1.FBUDGET_CENTER_ID=H.FBUDGET_CENTER_ID AND P1.FUSER_ID='+@LS_USER_ID+') THEN 0
	ELSE 1
	END AS FPERMISSION_VIEW,
	CASE
	WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_CONFIRM AS P2 WITH(NOLOCK) WHERE P2.FCATEGORY=''预算报账'' AND P2.FBUDGET_CENTER_ID=H.FBUDGET_CENTER_ID AND P2.FLEVEL=H.FLEVEL+1 AND P2.FUSER_ID='+@LS_USER_ID+') AND H.FSTATE=1 THEN 0
	ELSE 1
	END AS FPERMISSION_CONFIRM,
	CASE
	WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_CONFIRM AS P3 WITH(NOLOCK) WHERE P3.FCATEGORY=''预算报账'' AND P3.FBUDGET_CENTER_ID=H.FBUDGET_CENTER_ID AND P3.FLEVEL=H.FLEVEL AND P3.FUSER_ID='+@LS_USER_ID+') AND H.FSTATE IN (1,2) AND H.FLEVEL>0 AND NOT H.FLEVEL IS NULL THEN 0
	ELSE 1
	END AS FPERMISSION_UN_CONFIRM,
	CASE
	WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P4 WITH(NOLOCK) WHERE P4.FFUNCTIONID=970030000 AND P4.FUSERID='+@LS_USER_ID+' AND P4.FRIGHT=2) THEN 0
	ELSE 1
	END AS FPERMISSION_EDIT,
	CASE
	WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P5 WITH(NOLOCK) WHERE P5.FFUNCTIONID=970030000 AND P5.FUSERID='+@LS_USER_ID+' AND P5.FRIGHT=2 AND P5.FMODIFYOTHER=1) THEN 0
	ELSE 1
	END AS FPERMISSION_EDIT_ALL,
	CASE
	WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P5 WITH(NOLOCK) WHERE P5.FFUNCTIONID=970030100 AND P5.FUSERID='+@LS_USER_ID+' AND NOT P5.FRIGHT=0) AND H.FSTATE=2 THEN 0
	ELSE 1
	END AS FPERMISSION_TALLY,
	CASE
	WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P6 WITH(NOLOCK) WHERE P6.FFUNCTIONID=970030100 AND P6.FUSERID='+@LS_USER_ID+' AND NOT P6.FRIGHT=0) AND H.FSTATE=3 THEN 0
	ELSE 1
	END AS FPERMISSION_UN_TALLY,
	CASE
	WHEN CONVERT(CHAR(10),H.FDATE,20)>=ISNULL((SELECT CONVERT(CHAR(10),MIN(O1.FBEGDATE),20) FROM T_ACCOUNTPERIOD AS O1 WITH(NOLOCK) WHERE O1.FYEAR=(SELECT MAX(O2.FYEAR) FROM T_ACCOUNTPERIOD AS O2 WITH(NOLOCK) WHERE O2.FSTATUS=1) AND O1.FSTATUS=1),'''')
	AND CONVERT(CHAR(10),H.FDATE,20)<=ISNULL((SELECT CONVERT(CHAR(10),MAX(O3.FENDDATE),20) FROM T_ACCOUNTPERIOD AS O3 WITH(NOLOCK) WHERE O3.FYEAR=(SELECT MAX(O4.FYEAR) FROM T_ACCOUNTPERIOD AS O4 WITH(NOLOCK) WHERE O4.FSTATUS=1) AND O3.FSTATUS=1),'''')
	THEN 0
	ELSE
	1
	END AS FFILTER_PERIOD,
	H.FVALUE_BUDGET_CENTER_ID,
	(SELECT C3.FNO FROM T_BUDGET_CENTER AS C3 WITH(NOLOCK) WHERE C3.FID=H.FVALUE_BUDGET_CENTER_ID) AS FVALUE_BUDGET_CENTER_NO,
	(SELECT C4.FNAME FROM T_BUDGET_CENTER AS C4 WITH(NOLOCK) WHERE C4.FID=H.FVALUE_BUDGET_CENTER_ID) AS FVALUE_BUDGET_CENTER_NAME,
	D.FROW,
	D.FBUDGET_ITEM_ID,
	(SELECT I1.FNO FROM T_BUDGET_ITEM AS I1 WITH(NOLOCK) WHERE I1.FID=D.FBUDGET_ITEM_ID) AS FBUDGET_ITEM_NO,
	(SELECT I2.FNAME FROM T_BUDGET_ITEM AS I2 WITH(NOLOCK) WHERE I2.FID=D.FBUDGET_ITEM_ID) AS FBUDGET_ITEM_NAME,
(SELECT ASSITEM.FNAME FROM T_BUDGET_ASSISTANT_ITEM AS ASSITEM WITH(NOLOCK) WHERE ASSITEM.FID=D.FASSISTANT_ITEM_ID) AS FBUDGET_ASSISTANT_NAME,
	D.FAMOUNT,
	D.FCREDIT_ID,
	(SELECT A1.FACCOUNTNO FROM T_ACCOUNT AS A1 WITH(NOLOCK) WHERE A1.FACCID=D.FCREDIT_ID) AS FCREDIT_NO,
	(SELECT A2.FACCOUNTNAME FROM T_ACCOUNT AS A2 WITH(NOLOCK) WHERE A2.FACCID=D.FCREDIT_ID) AS FCREDIT_NAME,
	D.FDEBIT_ID,
	(SELECT A3.FACCOUNTNO FROM T_ACCOUNT AS A3 WITH(NOLOCK) WHERE A3.FACCID=D.FDEBIT_ID) AS FDEBIT_NO,
	(SELECT A4.FACCOUNTNAME FROM T_ACCOUNT AS A4 WITH(NOLOCK) WHERE A4.FACCID=D.FDEBIT_ID) AS FDEBIT_NAME,
	(SELECT C3.FPY FROM T_BUDGET_CENTER AS C3 WITH(NOLOCK) WHERE C3.FID=H.FBUDGET_CENTER_ID) AS FBUDGET_CNTER_PY,
	(SELECT I3.FPY FROM T_BUDGET_ITEM AS I3 WITH(NOLOCK) WHERE I3.FID=D.FBUDGET_ITEM_ID) AS FBUDGET_ITEM_PY,
	D.FPRODUCT_TYPE_ID,
	D.FPRODUCT_TYPE AS FDETAIL_PRODUCT_TYPE,
	CASE D.FPRODUCT_TYPE
	WHEN ''TOP'' THEN (SELECT T.FNAME FROM T_BATCHNO_PRODTYPE AS T WITH(NOLOCK) WHERE T.FID=D.FPRODUCT_TYPE_ID)
	WHEN ''CHILDREN'' THEN (SELECT C.FONENAME+'' - ''+C.FTWONAME FROM T_BATCHNO_CLASS AS C WITH(NOLOCK) WHERE C.FID=D.FPRODUCT_TYPE_ID)
	END AS FPRODUCT_TYPE_NAME,
	H.FCONFIRM_STATE,
	D.FREVISE,
	H.FPRODUCT_TYPE,
	(SELECT SUM(RD.FAMOUNT) FROM T_BUDGET_REPORT_DETAIL AS RD WITH(NOLOCK) WHERE RD.FID=H.FID) AS FAMOUNT_SUM,
	D.FSUMMARY,
	D.FEMPLOYEE_ID,
	(SELECT E1.FNO FROM T_EMP AS E1 WITH(NOLOCK) WHERE E1.FINTERID=D.FEMPLOYEE_ID) AS FEMPLOYEE_NO,
	(SELECT E2.FNAME FROM T_EMP AS E2 WITH(NOLOCK) WHERE E2.FINTERID=D.FEMPLOYEE_ID) AS FEMPLOYEE_NAME,
	H.FDEPARTMENT_ID,
	(SELECT D1.FCODE FROM T_DEPARTMENT AS D1 WITH(NOLOCK) WHERE D1.FINTERID=H.FDEPARTMENT_ID) AS FDEPARTMENT_NO,
	(SELECT D2.FDMNAME FROM T_DEPARTMENT AS D2 WITH(NOLOCK) WHERE D2.FINTERID=H.FDEPARTMENT_ID) AS FDEPARTMENT_NAME,
	H.FDEPARTMENT,
	G.FNAME+CAST(V.FNUMBER AS VARCHAR(200)) AS FKINGDEE_VOUCHER_CODE,
	H.FCHECK,
	D.FSELL_YEAR,
	H.FINHERIT_MANAGEMENT_MATERIAL
	FROM (
	SELECT
	RH.*,
	CASE
	WHEN EXISTS(
	SELECT
	1
	FROM TIC_INSTOCKITEMS QD WITH(NOLOCK)
	WHERE
	QD.FBUDGET_REPORT_ID=RH.FID
	) THEN ''是''
	ELSE ''否''
	END ''FINHERIT_MANAGEMENT_MATERIAL''
	FROM T_BUDGET_REPORT_HEADER RH WITH(NOLOCK)
	) H
	INNER JOIN T_BUDGET_REPORT_DETAIL AS D WITH(NOLOCK) ON D.FID=H.FID
	LEFT JOIN T_FI_ACCDOC AS F WITH(NOLOCK) ON F.FACCTDOCID=H.FVOUCHER_ID
	LEFT JOIN OPENROWSET(''SQLOLEDB'','''+@LS_SERVER+''';'''+@LS_USER+'''; '''+@LS_PASSWORD+''', '+@LS_DATABASE+'.DBO.T_VOUCHER) V ON V.FSERIALNUM=F.FK3SERIALNUMBER
	LEFT JOIN OPENROWSET(''SQLOLEDB'','''+@LS_SERVER+''';'''+@LS_USER+''';'''+@LS_PASSWORD+''', '+@LS_DATABASE+'.DBO.T_VOUCHERGROUP) G ON G.FGROUPID=V.FGROUPID
	'
	
END

IF @LS_CATEGORY='预算报账' AND @LS_NON_DETAIL='是'
BEGIN
	
	SET @LS_SQL=
	'SELECT
	H.FID,
	H.FNO,
	H.FBUDGET_CENTER_ID,
	(SELECT C1.FNO FROM T_BUDGET_CENTER AS C1 WITH(NOLOCK) WHERE C1.FID=H.FBUDGET_CENTER_ID) AS FBUDGET_CENTER_NO,
	(SELECT C2.FNAME FROM T_BUDGET_CENTER AS C2 WITH(NOLOCK) WHERE C2.FID=H.FBUDGET_CENTER_ID) AS FBUDGET_CENTER_NAME,
	H.FDATE,
	H.FSTATE,
	H.FREMARK,
	H.FCREATE_ID,
	(SELECT U1.FNAME FROM T_USER AS U1 WITH(NOLOCK) WHERE U1.FINTERID=H.FCREATE_ID) AS FCREATE,
	H.FCREATE_DATE,
	H.FCONFIRM_ID,
	(SELECT U2.FNAME FROM T_USER AS U2 WITH(NOLOCK) WHERE U2.FINTERID=H.FCONFIRM_ID) AS FCONFIRM,
	H.FCONFIRM_DATE,
	H.FTALLY_ID,
	(SELECT U3.FNAME FROM T_USER AS U3 WITH(NOLOCK) WHERE U3.FINTERID=H.FTALLY_ID) AS FTALLY,
	H.FTALLY_DATE,
	H.FVOUCHER_ID,
	H.FLEVEL,
	CASE
	WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_VIEW AS P1 WITH(NOLOCK) WHERE P1.FCATEGORY=''预算报账'' AND P1.FBUDGET_CENTER_ID=H.FBUDGET_CENTER_ID AND P1.FUSER_ID='+@LS_USER_ID+') THEN 0
	ELSE 1
	END AS FPERMISSION_VIEW,
	CASE
	WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_CONFIRM AS P2 WITH(NOLOCK) WHERE P2.FCATEGORY=''预算报账'' AND P2.FBUDGET_CENTER_ID=H.FBUDGET_CENTER_ID AND P2.FLEVEL=H.FLEVEL+1 AND P2.FUSER_ID='+@LS_USER_ID+') AND H.FSTATE=1 THEN 0
	ELSE 1
	END AS FPERMISSION_CONFIRM,
	CASE
	WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_CONFIRM AS P3 WITH(NOLOCK) WHERE P3.FCATEGORY=''预算报账'' AND P3.FBUDGET_CENTER_ID=H.FBUDGET_CENTER_ID AND P3.FLEVEL=H.FLEVEL AND P3.FUSER_ID='+@LS_USER_ID+') AND H.FSTATE IN (1,2) AND H.FLEVEL>0 AND NOT H.FLEVEL IS NULL THEN 0
	ELSE 1
	END AS FPERMISSION_UN_CONFIRM,
	CASE
	WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P4 WITH(NOLOCK) WHERE P4.FFUNCTIONID=970030000 AND P4.FUSERID='+@LS_USER_ID+' AND P4.FRIGHT=2) THEN 0
	ELSE 1
	END AS FPERMISSION_EDIT,
	CASE
	WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P5 WITH(NOLOCK) WHERE P5.FFUNCTIONID=970030000 AND P5.FUSERID='+@LS_USER_ID+' AND P5.FRIGHT=2 AND P5.FMODIFYOTHER=1) THEN 0
	ELSE 1
	END AS FPERMISSION_EDIT_ALL,
	CASE
	WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P5 WITH(NOLOCK) WHERE P5.FFUNCTIONID=970030100 AND P5.FUSERID='+@LS_USER_ID+' AND NOT P5.FRIGHT=0) AND H.FSTATE=2 THEN 0
	ELSE 1
	END AS FPERMISSION_TALLY,
	CASE
	WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P6 WITH(NOLOCK) WHERE P6.FFUNCTIONID=970030100 AND P6.FUSERID='+@LS_USER_ID+' AND NOT P6.FRIGHT=0) AND H.FSTATE=3 THEN 0
	ELSE 1
	END AS FPERMISSION_UN_TALLY,
	CASE
	WHEN CONVERT(CHAR(10),H.FDATE,20)>=ISNULL((SELECT CONVERT(CHAR(10),MIN(O1.FBEGDATE),20) FROM T_ACCOUNTPERIOD AS O1 WITH(NOLOCK) WHERE O1.FYEAR=(SELECT MAX(O2.FYEAR) FROM T_ACCOUNTPERIOD AS O2 WITH(NOLOCK) WHERE O2.FSTATUS=1) AND O1.FSTATUS=1),'''')
	AND CONVERT(CHAR(10),H.FDATE,20)<=ISNULL((SELECT CONVERT(CHAR(10),MAX(O3.FENDDATE),20) FROM T_ACCOUNTPERIOD AS O3 WITH(NOLOCK) WHERE O3.FYEAR=(SELECT MAX(O4.FYEAR) FROM T_ACCOUNTPERIOD AS O4 WITH(NOLOCK) WHERE O4.FSTATUS=1) AND O3.FSTATUS=1),'''')
	THEN 0
	ELSE
	1
	END AS FFILTER_PERIOD,
	H.FVALUE_BUDGET_CENTER_ID,
	(SELECT C3.FNO FROM T_BUDGET_CENTER AS C3 WITH(NOLOCK) WHERE C3.FID=H.FVALUE_BUDGET_CENTER_ID) AS FVALUE_BUDGET_CENTER_NO,
	(SELECT C4.FNAME FROM T_BUDGET_CENTER AS C4 WITH(NOLOCK) WHERE C4.FID=H.FVALUE_BUDGET_CENTER_ID) AS FVALUE_BUDGET_CENTER_NAME,
	(SELECT C3.FPY FROM T_BUDGET_CENTER AS C3 WITH(NOLOCK) WHERE C3.FID=H.FBUDGET_CENTER_ID) AS FBUDGET_CNTER_PY,
	H.FCONFIRM_STATE,
	H.FPRODUCT_TYPE,
	(SELECT SUM(RD.FAMOUNT) FROM T_BUDGET_REPORT_DETAIL AS RD WITH(NOLOCK) WHERE RD.FID=H.FID) AS FAMOUNT_SUM,
	H.FDEPARTMENT_ID,
	(SELECT D1.FCODE FROM T_DEPARTMENT AS D1 WITH(NOLOCK) WHERE D1.FINTERID=H.FDEPARTMENT_ID) AS FDEPARTMENT_NO,
	(SELECT D2.FDMNAME FROM T_DEPARTMENT AS D2 WITH(NOLOCK) WHERE D2.FINTERID=H.FDEPARTMENT_ID) AS FDEPARTMENT_NAME,
	H.FDEPARTMENT,
	G.FNAME+CAST(V.FNUMBER AS VARCHAR(200)) AS FKINGDEE_VOUCHER_CODE,
	H.FCHECK,
	H.FINHERIT_MANAGEMENT_MATERIAL
	FROM (
	SELECT
	RH.*,
	CASE
	WHEN EXISTS(
	SELECT
	1
	FROM TIC_INSTOCKITEMS QD WITH(NOLOCK)
	WHERE
	QD.FBUDGET_REPORT_ID=RH.FID
	) THEN ''是''
	ELSE ''否''
	END ''FINHERIT_MANAGEMENT_MATERIAL''
	FROM T_BUDGET_REPORT_HEADER RH WITH(NOLOCK)
	) H
	INNER JOIN T_BUDGET_REPORT_DETAIL AS D WITH(NOLOCK) ON D.FID=H.FID
	LEFT JOIN T_FI_ACCDOC AS F WITH(NOLOCK) ON F.FACCTDOCID=H.FVOUCHER_ID
	LEFT JOIN OPENROWSET(''SQLOLEDB'','''+@LS_SERVER+''';'''+@LS_USER+'''; '''+@LS_PASSWORD+''', '+@LS_DATABASE+'.DBO.T_VOUCHER) V ON V.FSERIALNUM=F.FK3SERIALNUMBER
	LEFT JOIN OPENROWSET(''SQLOLEDB'','''+@LS_SERVER+''';'''+@LS_USER+''';'''+@LS_PASSWORD+''', '+@LS_DATABASE+'.DBO.T_VOUCHERGROUP) G ON G.FGROUPID=V.FGROUPID
	'
	
END

IF @LS_CATEGORY='差旅费报账' AND @LS_NON_DETAIL='否'
BEGIN
	
	SET @LS_SQL=
	'SELECT
	B.FID,
	B.FNO,
	B.FSTATE,
	B.FDEPARTMENTID,
	(SELECT ''(''+P.FCODE+'')''+P.FDMNAME FROM T_DEPARTMENT AS P WITH(NOLOCK) WHERE P.FINTERID=B.FDEPARTMENTID) AS FDEPARTMENT,
	B.FEMPID,
	(SELECT ''(''+E.FNO+'')''+E.FNAME FROM T_EMP AS E WITH(NOLOCK) WHERE E.FINTERID=B.FEMPID) AS FEMP,
	B.FCONTENT,
	B.FDATE,
	B.FUSERID,
	(SELECT U1.FNAME FROM T_USER AS U1 WITH(NOLOCK) WHERE U1.FINTERID=B.FUSERID) AS FUSER,
	(SELECT SUM(D.FAMOUNT) FROM T_BT_D AS D WITH(NOLOCK) WHERE D.FID=B.FID) AS FAMOUNT,
	B.FLEVEL,
	B.FBUDGETCENTERID,
	(SELECT C.FNO FROM T_BUDGET_CENTER AS C WITH(NOLOCK) WHERE C.FID=B.FBUDGETCENTERID) AS FBUDGET_CENTER_NO,
	B.FBUDGETITEMID,
	(SELECT I.FNO FROM T_BUDGET_ITEM AS I WITH(NOLOCK) WHERE I.FID=B.FBUDGETITEMID) AS FBUDGET_ITEM_NO,
	B.FPERIOD,
	B.FDEBIT_ID AS FACCOUNTID,
	(SELECT ''(''+A1.FACCOUNTNO+'')''+A1.FACCOUNTNAME FROM T_ACCOUNT AS A1 WITH(NOLOCK) WHERE A1.FACCID=B.FDEBIT_ID) AS FACCOUNT,
	B.FACCDOCID,
	B.FCREDITACCID,
	(SELECT ''(''+A1.FACCOUNTNO+'')''+A1.FACCOUNTNAME FROM T_ACCOUNT AS A1 WITH(NOLOCK) WHERE A1.FACCID=B.FCREDITACCID) AS FCREDITACC,
	(SELECT D1.FDOCNO FROM T_FI_ACCDOC AS D1 WITH(NOLOCK) WHERE D1.FACCTDOCID=B.FACCDOCID) AS FACCDOC,
	CASE
	WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_VIEW AS P1 WITH(NOLOCK) WHERE P1.FCATEGORY=''差旅费报账'' AND P1.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND P1.FUSER_ID='+@LS_USER_ID+') THEN 0
	ELSE 1
	END AS FPERMISSION_VIEW,
	CASE
	WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_CONFIRM AS P2 WITH(NOLOCK) WHERE P2.FCATEGORY=''差旅费报账'' AND P2.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND P2.FLEVEL=B.FLEVEL+1 AND P2.FUSER_ID='+@LS_USER_ID+') AND B.FSTATE=1 THEN 0
	ELSE 1
	END AS FPERMISSION_CONFIRM,
	CASE
	WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_CONFIRM AS P3 WITH(NOLOCK) WHERE P3.FCATEGORY=''差旅费报账'' AND P3.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND P3.FLEVEL=B.FLEVEL AND P3.FUSER_ID='+@LS_USER_ID+') AND B.FSTATE IN (1,2) AND B.FLEVEL>0 AND NOT B.FLEVEL IS NULL THEN 0
	ELSE 1
	END AS FPERMISSION_UN_CONFIRM,
	CASE
	WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P4 WITH(NOLOCK) WHERE P4.FFUNCTIONID=970030200 AND P4.FUSERID='+@LS_USER_ID+' AND P4.FRIGHT=2) THEN 0
	ELSE 1
	END AS FPERMISSION_EDIT,
	CASE
	WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P5 WITH(NOLOCK) WHERE P5.FFUNCTIONID=970030200 AND P5.FUSERID='+@LS_USER_ID+' AND P5.FRIGHT=2 AND P5.FMODIFYOTHER=1) THEN 0
	ELSE 1
	END AS FPERMISSION_EDIT_ALL,
	CASE
	WHEN CONVERT(CHAR(10),B.FPERIOD,20)>=ISNULL((SELECT CONVERT(CHAR(10),MIN(O1.FBEGDATE),20) FROM T_ACCOUNTPERIOD AS O1 WITH(NOLOCK) WHERE O1.FYEAR=(SELECT MAX(O2.FYEAR) FROM T_ACCOUNTPERIOD AS O2 WITH(NOLOCK) WHERE O2.FSTATUS=1) AND O1.FSTATUS=1),'''')
	AND CONVERT(CHAR(10),B.FPERIOD,20)<=ISNULL((SELECT CONVERT(CHAR(10),MAX(O3.FENDDATE),20) FROM T_ACCOUNTPERIOD AS O3 WITH(NOLOCK) WHERE O3.FYEAR=(SELECT MAX(O4.FYEAR) FROM T_ACCOUNTPERIOD AS O4 WITH(NOLOCK) WHERE O4.FSTATUS=1) AND O3.FSTATUS=1),'''')
	THEN 0
	ELSE
	1
	END AS FFILTER_PERIOD,
	B.FVALUE_BUDGET_CENTER_ID,
	(SELECT C3.FNO FROM T_BUDGET_CENTER AS C3 WITH(NOLOCK) WHERE C3.FID=B.FVALUE_BUDGET_CENTER_ID) AS FVALUE_BUDGET_CENTER_NO,
	(SELECT C4.FNAME FROM T_BUDGET_CENTER AS C4 WITH(NOLOCK) WHERE C4.FID=B.FVALUE_BUDGET_CENTER_ID) AS FVALUE_BUDGET_CENTER_NAME,
	CASE
	WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P5 WITH(NOLOCK) WHERE P5.FFUNCTIONID=970030100 AND P5.FUSERID='+@LS_USER_ID+' AND NOT P5.FRIGHT=0) AND B.FSTATE=2 THEN 0
	ELSE 1
	END AS FPERMISSION_TALLY,
	CASE
	WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P6 WITH(NOLOCK) WHERE P6.FFUNCTIONID=970030100 AND P6.FUSERID='+@LS_USER_ID+' AND NOT P6.FRIGHT=0) AND B.FSTATE=3 THEN 0
	ELSE 1
	END AS FPERMISSION_UN_TALLY,
	B.FCONFIRM_ID,
	(SELECT U2.FNAME FROM T_USER AS U2 WITH(NOLOCK) WHERE U2.FINTERID=B.FCONFIRM_ID) AS FCONFIRM,
	B.FCONFIRM_DATE,
	B.FTALLY_ID,
	(SELECT U3.FNAME FROM T_USER AS U3 WITH(NOLOCK) WHERE U3.FINTERID=B.FTALLY_ID) AS FTALLY,
	B.FTALLY_DATE,
	D.FITEMID,
	(SELECT I.FNAME FROM T_BT_I AS I WITH(NOLOCK) WHERE I.FID=D.FITEMID) AS FITEM,
	D.FCONTENT AS FCONTENT_DETAIL,
	D.FCONTENT2 AS FCONTENT2_DETAIL,
	D.FAMOUNT AS FDETAIL_AMOUNT,
	D.FNO AS FNO_DETAIL,
	D.FREMARK AS FREMARK_DETAIL,
	(SELECT C3.FPY FROM T_BUDGET_CENTER AS C3 WITH(NOLOCK) WHERE C3.FID=B.FBUDGETCENTERID) AS FBUDGET_CNTER_PY,
	(SELECT I3.FPY FROM T_BUDGET_ITEM AS I3 WITH(NOLOCK) WHERE I3.FID=B.FBUDGETITEMID) AS FBUDGET_ITEM_PY,
	B.FCONFIRM_STATE,
	D.FSTANDARD AS FDETAIL_STANDARD,
	D.FAPPLY AS FDETAIL_APPLY,
	B.FPRODUCT_TYPE,
	(SELECT C.FNAME FROM T_BUDGET_CENTER AS C WITH(NOLOCK) WHERE C.FID=B.FBUDGETCENTERID) AS FBUDGET_CENTER_NAME,
	(SELECT I.FNAME FROM T_BUDGET_ITEM AS I WITH(NOLOCK) WHERE I.FID=B.FBUDGETITEMID) AS FBUDGET_ITEM_NAME,
(SELECT ASSITEM.FNAME FROM T_BUDGET_ASSISTANT_ITEM AS ASSITEM WITH(NOLOCK) WHERE ASSITEM.FID=B.FASSISTANT_ITEM_ID) AS FBUDGET_ASSISTANT_NAME,
	G.FNAME+CAST(V.FNUMBER AS VARCHAR(200)) AS FKINGDEE_VOUCHER_CODE,
	B.FCHECK
	FROM T_BT AS B WITH(NOLOCK)	INNER JOIN T_BT_D AS D WITH(NOLOCK) ON D.FID=B.FID
	LEFT JOIN T_FI_ACCDOC AS F WITH(NOLOCK) ON F.FACCTDOCID=B.FACCDOCID
	LEFT JOIN OPENROWSET(''SQLOLEDB'','''+@LS_SERVER+''';'''+@LS_USER+'''; '''+@LS_PASSWORD+''', '+@LS_DATABASE+'.DBO.T_VOUCHER) V ON V.FSERIALNUM=F.FK3SERIALNUMBER
	LEFT JOIN OPENROWSET(''SQLOLEDB'','''+@LS_SERVER+''';'''+@LS_USER+''';'''+@LS_PASSWORD+''', '+@LS_DATABASE+'.DBO.T_VOUCHERGROUP) G ON G.FGROUPID=V.FGROUPID
	'
	
END

IF @LS_CATEGORY='差旅费报账' AND @LS_NON_DETAIL='是'
BEGIN
	
	SET @LS_SQL=
	'SELECT
	B.FID,
	B.FNO,
	B.FSTATE,
	B.FDEPARTMENTID,
	(SELECT ''(''+P.FCODE+'')''+P.FDMNAME FROM T_DEPARTMENT AS P WITH(NOLOCK) WHERE P.FINTERID=B.FDEPARTMENTID) AS FDEPARTMENT,
	B.FEMPID,
	(SELECT ''(''+E.FNO+'')''+E.FNAME FROM T_EMP AS E WITH(NOLOCK) WHERE E.FINTERID=B.FEMPID) AS FEMP,
	B.FCONTENT,
	B.FDATE,
	B.FUSERID,
	(SELECT U1.FNAME FROM T_USER AS U1 WITH(NOLOCK) WHERE U1.FINTERID=B.FUSERID) AS FUSER,
	(SELECT SUM(D.FAMOUNT) FROM T_BT_D AS D WITH(NOLOCK) WHERE D.FID=B.FID) AS FAMOUNT,
	B.FLEVEL,
	B.FBUDGETCENTERID,
	(SELECT C.FNO FROM T_BUDGET_CENTER AS C WITH(NOLOCK) WHERE C.FID=B.FBUDGETCENTERID) AS FBUDGET_CENTER_NO,
	B.FBUDGETITEMID,
	(SELECT I.FNO FROM T_BUDGET_ITEM AS I WITH(NOLOCK) WHERE I.FID=B.FBUDGETITEMID) AS FBUDGET_ITEM_NO,
	B.FPERIOD,
	(SELECT IC1.FDEBIT_ID FROM T_BUDGET_CENTER_ITEM AS IC1 WITH(NOLOCK) WHERE IC1.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND IC1.FBUDGET_ITEM_ID=B.FBUDGETITEMID) AS FACCOUNTID,
	(SELECT (SELECT ''(''+A1.FACCOUNTNO+'')''+A1.FACCOUNTNAME FROM T_ACCOUNT AS A1 WITH(NOLOCK) WHERE A1.FACCID=IC2.FDEBIT_ID) FROM T_BUDGET_CENTER_ITEM AS IC2 WITH(NOLOCK) WHERE IC2.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND IC2.FBUDGET_ITEM_ID=B.FBUDGETITEMID) AS FACCOUNT,
	B.FACCDOCID,
	B.FCREDITACCID,
	(SELECT ''(''+A1.FACCOUNTNO+'')''+A1.FACCOUNTNAME FROM T_ACCOUNT AS A1 WITH(NOLOCK) WHERE A1.FACCID=B.FCREDITACCID) AS FCREDITACC,
	(SELECT D1.FDOCNO FROM T_FI_ACCDOC AS D1 WITH(NOLOCK) WHERE D1.FACCTDOCID=B.FACCDOCID) AS FACCDOC,
	CASE
	WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_VIEW AS P1 WITH(NOLOCK) WHERE P1.FCATEGORY=''差旅费报账'' AND P1.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND P1.FUSER_ID='+@LS_USER_ID+') THEN 0
	ELSE 1
	END AS FPERMISSION_VIEW,
	CASE
	WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_CONFIRM AS P2 WITH(NOLOCK) WHERE P2.FCATEGORY=''差旅费报账'' AND P2.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND P2.FLEVEL=B.FLEVEL+1 AND P2.FUSER_ID='+@LS_USER_ID+') AND B.FSTATE=1 THEN 0
	ELSE 1
	END AS FPERMISSION_CONFIRM,
	CASE
	WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_CONFIRM AS P3 WITH(NOLOCK) WHERE P3.FCATEGORY=''差旅费报账'' AND P3.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND P3.FLEVEL=B.FLEVEL AND P3.FUSER_ID='+@LS_USER_ID+') AND B.FSTATE IN (1,2) AND B.FLEVEL>0 AND NOT B.FLEVEL IS NULL THEN 0
	ELSE 1
	END AS FPERMISSION_UN_CONFIRM,
	CASE
	WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P4 WITH(NOLOCK) WHERE P4.FFUNCTIONID=970030200 AND P4.FUSERID='+@LS_USER_ID+' AND P4.FRIGHT=2) THEN 0
	ELSE 1
	END AS FPERMISSION_EDIT,
	CASE
	WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P5 WITH(NOLOCK) WHERE P5.FFUNCTIONID=970030200 AND P5.FUSERID='+@LS_USER_ID+' AND P5.FRIGHT=2 AND P5.FMODIFYOTHER=1) THEN 0
	ELSE 1
	END AS FPERMISSION_EDIT_ALL,
	CASE
	WHEN CONVERT(CHAR(10),B.FPERIOD,20)>=ISNULL((SELECT CONVERT(CHAR(10),MIN(O1.FBEGDATE),20) FROM T_ACCOUNTPERIOD AS O1 WITH(NOLOCK) WHERE O1.FYEAR=(SELECT MAX(O2.FYEAR) FROM T_ACCOUNTPERIOD AS O2 WITH(NOLOCK) WHERE O2.FSTATUS=1) AND O1.FSTATUS=1),'''')
	AND CONVERT(CHAR(10),B.FPERIOD,20)<=ISNULL((SELECT CONVERT(CHAR(10),MAX(O3.FENDDATE),20) FROM T_ACCOUNTPERIOD AS O3 WITH(NOLOCK) WHERE O3.FYEAR=(SELECT MAX(O4.FYEAR) FROM T_ACCOUNTPERIOD AS O4 WITH(NOLOCK) WHERE O4.FSTATUS=1) AND O3.FSTATUS=1),'''')
	THEN 0
	ELSE
	1
	END AS FFILTER_PERIOD,
	B.FVALUE_BUDGET_CENTER_ID,
	(SELECT C3.FNO FROM T_BUDGET_CENTER AS C3 WITH(NOLOCK) WHERE C3.FID=B.FVALUE_BUDGET_CENTER_ID) AS FVALUE_BUDGET_CENTER_NO,
	(SELECT C4.FNAME FROM T_BUDGET_CENTER AS C4 WITH(NOLOCK) WHERE C4.FID=B.FVALUE_BUDGET_CENTER_ID) AS FVALUE_BUDGET_CENTER_NAME,
	CASE
	WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P5 WITH(NOLOCK) WHERE P5.FFUNCTIONID=970030100 AND P5.FUSERID='+@LS_USER_ID+' AND NOT P5.FRIGHT=0) AND B.FSTATE=2 THEN 0
	ELSE 1
	END AS FPERMISSION_TALLY,
	CASE
	WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P6 WITH(NOLOCK) WHERE P6.FFUNCTIONID=970030100 AND P6.FUSERID='+@LS_USER_ID+' AND NOT P6.FRIGHT=0) AND B.FSTATE=3 THEN 0
	ELSE 1
	END AS FPERMISSION_UN_TALLY,
	B.FCONFIRM_ID,
	(SELECT U2.FNAME FROM T_USER AS U2 WITH(NOLOCK) WHERE U2.FINTERID=B.FCONFIRM_ID) AS FCONFIRM,
	B.FCONFIRM_DATE,
	B.FTALLY_ID,
	(SELECT U3.FNAME FROM T_USER AS U3 WITH(NOLOCK) WHERE U3.FINTERID=B.FTALLY_ID) AS FTALLY,
	B.FTALLY_DATE,
	(SELECT C3.FPY FROM T_BUDGET_CENTER AS C3 WITH(NOLOCK) WHERE C3.FID=B.FBUDGETCENTERID) AS FBUDGET_CNTER_PY,
	(SELECT I3.FPY FROM T_BUDGET_ITEM AS I3 WITH(NOLOCK) WHERE I3.FID=B.FBUDGETITEMID) AS FBUDGET_ITEM_PY,
	B.FCONFIRM_STATE,
	B.FPRODUCT_TYPE,
	(SELECT C.FNAME FROM T_BUDGET_CENTER AS C WITH(NOLOCK) WHERE C.FID=B.FBUDGETCENTERID) AS FBUDGET_CENTER_NAME,
	(SELECT I.FNAME FROM T_BUDGET_ITEM AS I WITH(NOLOCK) WHERE I.FID=B.FBUDGETITEMID) AS FBUDGET_ITEM_NAME,
(SELECT ASSITEM.FNAME FROM T_BUDGET_ASSISTANT_ITEM AS ASSITEM WITH(NOLOCK) WHERE ASSITEM.FID=B.FASSISTANT_ITEM_ID) AS FBUDGET_ASSISTANT_NAME,
	G.FNAME+CAST(V.FNUMBER AS VARCHAR(200)) AS FKINGDEE_VOUCHER_CODE,
	B.FCHECK
	FROM T_BT AS B WITH(NOLOCK)
	LEFT JOIN T_FI_ACCDOC AS F WITH(NOLOCK) ON F.FACCTDOCID=B.FACCDOCID
	LEFT JOIN OPENROWSET(''SQLOLEDB'','''+@LS_SERVER+''';'''+@LS_USER+'''; '''+@LS_PASSWORD+''', '+@LS_DATABASE+'.DBO.T_VOUCHER) V ON V.FSERIALNUM=F.FK3SERIALNUMBER
	LEFT JOIN OPENROWSET(''SQLOLEDB'','''+@LS_SERVER+''';'''+@LS_USER+''';'''+@LS_PASSWORD+''', '+@LS_DATABASE+'.DBO.T_VOUCHERGROUP) G ON G.FGROUPID=V.FGROUPID
	'
	
END

IF @LS_CATEGORY='差旅费报账_产品类别'
BEGIN
	
	SET @LS_SQL=
	'SELECT
	B.FID,
	B.FNO,
	B.FSTATE,
	B.FDEPARTMENTID,
	(SELECT ''(''+P.FCODE+'')''+P.FDMNAME FROM T_DEPARTMENT AS P WITH(NOLOCK) WHERE P.FINTERID=B.FDEPARTMENTID) AS FDEPARTMENT,
	B.FEMPID,
	(SELECT ''(''+E.FNO+'')''+E.FNAME FROM T_EMP AS E WITH(NOLOCK) WHERE E.FINTERID=B.FEMPID) AS FEMP,
	B.FCONTENT,
	B.FDATE,
	B.FUSERID,
	(SELECT U1.FNAME FROM T_USER AS U1 WITH(NOLOCK) WHERE U1.FINTERID=B.FUSERID) AS FUSER,
	(SELECT SUM(D.FAMOUNT) FROM T_BT_D AS D WITH(NOLOCK) WHERE D.FID=B.FID) AS FAMOUNT,
	B.FLEVEL,
	B.FBUDGETCENTERID,
	(SELECT C.FNO FROM T_BUDGET_CENTER AS C WITH(NOLOCK) WHERE C.FID=B.FBUDGETCENTERID) AS FBUDGET_CENTER_NO,
	B.FBUDGETITEMID,
	(SELECT I.FNO FROM T_BUDGET_ITEM AS I WITH(NOLOCK) WHERE I.FID=B.FBUDGETITEMID) AS FBUDGET_ITEM_NO,
	B.FPERIOD,
	B.FDEBIT_ID AS FACCOUNTID,
	(SELECT ''(''+A1.FACCOUNTNO+'')''+A1.FACCOUNTNAME FROM T_ACCOUNT AS A1 WITH(NOLOCK) WHERE A1.FACCID=B.FDEBIT_ID) AS FACCOUNT,
	B.FACCDOCID,
	B.FCREDITACCID,
	(SELECT ''(''+A1.FACCOUNTNO+'')''+A1.FACCOUNTNAME FROM T_ACCOUNT AS A1 WITH(NOLOCK) WHERE A1.FACCID=B.FCREDITACCID) AS FCREDITACC,
	(SELECT D1.FDOCNO FROM T_FI_ACCDOC AS D1 WITH(NOLOCK) WHERE D1.FACCTDOCID=B.FACCDOCID) AS FACCDOC,
	CASE
	WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_VIEW AS P1 WITH(NOLOCK) WHERE P1.FCATEGORY=''差旅费报账'' AND P1.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND P1.FUSER_ID='+@LS_USER_ID+') THEN 0
	ELSE 1
	END AS FPERMISSION_VIEW,
	CASE
	WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_CONFIRM AS P2 WITH(NOLOCK) WHERE P2.FCATEGORY=''差旅费报账'' AND P2.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND P2.FLEVEL=B.FLEVEL+1 AND P2.FUSER_ID='+@LS_USER_ID+') AND B.FSTATE=1 THEN 0
	ELSE 1
	END AS FPERMISSION_CONFIRM,
	CASE
	WHEN EXISTS(SELECT * FROM T_BUDGET_PERMISSION_CONFIRM AS P3 WITH(NOLOCK) WHERE P3.FCATEGORY=''差旅费报账'' AND P3.FBUDGET_CENTER_ID=B.FBUDGETCENTERID AND P3.FLEVEL=B.FLEVEL AND P3.FUSER_ID='+@LS_USER_ID+') AND B.FSTATE IN (1,2) AND B.FLEVEL>0 AND NOT B.FLEVEL IS NULL THEN 0
	ELSE 1
	END AS FPERMISSION_UN_CONFIRM,
	CASE
	WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P4 WITH(NOLOCK) WHERE P4.FFUNCTIONID=970030200 AND P4.FUSERID='+@LS_USER_ID+' AND P4.FRIGHT=2) THEN 0
	ELSE 1
	END AS FPERMISSION_EDIT,
	CASE
	WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P5 WITH(NOLOCK) WHERE P5.FFUNCTIONID=970030200 AND P5.FUSERID='+@LS_USER_ID+' AND P5.FRIGHT=2 AND P5.FMODIFYOTHER=1) THEN 0
	ELSE 1
	END AS FPERMISSION_EDIT_ALL,
	CASE
	WHEN CONVERT(CHAR(10),B.FPERIOD,20)>=ISNULL((SELECT CONVERT(CHAR(10),MIN(O1.FBEGDATE),20) FROM T_ACCOUNTPERIOD AS O1 WITH(NOLOCK) WHERE O1.FYEAR=(SELECT MAX(O2.FYEAR) FROM T_ACCOUNTPERIOD AS O2 WITH(NOLOCK) WHERE O2.FSTATUS=1) AND O1.FSTATUS=1),'''')
	AND CONVERT(CHAR(10),B.FPERIOD,20)<=ISNULL((SELECT CONVERT(CHAR(10),MAX(O3.FENDDATE),20) FROM T_ACCOUNTPERIOD AS O3 WITH(NOLOCK) WHERE O3.FYEAR=(SELECT MAX(O4.FYEAR) FROM T_ACCOUNTPERIOD AS O4 WITH(NOLOCK) WHERE O4.FSTATUS=1) AND O3.FSTATUS=1),'''')
	THEN 0
	ELSE
	1
	END AS FFILTER_PERIOD,
	B.FVALUE_BUDGET_CENTER_ID,
	(SELECT C3.FNO FROM T_BUDGET_CENTER AS C3 WITH(NOLOCK) WHERE C3.FID=B.FVALUE_BUDGET_CENTER_ID) AS FVALUE_BUDGET_CENTER_NO,
	(SELECT C4.FNAME FROM T_BUDGET_CENTER AS C4 WITH(NOLOCK) WHERE C4.FID=B.FVALUE_BUDGET_CENTER_ID) AS FVALUE_BUDGET_CENTER_NAME,
	CASE
	WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P5 WITH(NOLOCK) WHERE P5.FFUNCTIONID=970030100 AND P5.FUSERID='+@LS_USER_ID+' AND NOT P5.FRIGHT=0) AND B.FSTATE=2 THEN 0
	ELSE 1
	END AS FPERMISSION_TALLY,
	CASE
	WHEN EXISTS(SELECT * FROM T_USERRIGHT AS P6 WITH(NOLOCK) WHERE P6.FFUNCTIONID=970030100 AND P6.FUSERID='+@LS_USER_ID+' AND NOT P6.FRIGHT=0) AND B.FSTATE=3 THEN 0
	ELSE 1
	END AS FPERMISSION_UN_TALLY,
	B.FCONFIRM_ID,
	(SELECT U2.FNAME FROM T_USER AS U2 WITH(NOLOCK) WHERE U2.FINTERID=B.FCONFIRM_ID) AS FCONFIRM,
	B.FCONFIRM_DATE,
	B.FTALLY_ID,
	(SELECT U3.FNAME FROM T_USER AS U3 WITH(NOLOCK) WHERE U3.FINTERID=B.FTALLY_ID) AS FTALLY,
	B.FTALLY_DATE,
	(SELECT C3.FPY FROM T_BUDGET_CENTER AS C3 WITH(NOLOCK) WHERE C3.FID=B.FBUDGETCENTERID) AS FBUDGET_CNTER_PY,
	(SELECT I3.FPY FROM T_BUDGET_ITEM AS I3 WITH(NOLOCK) WHERE I3.FID=B.FBUDGETITEMID) AS FBUDGET_ITEM_PY,
	B.FCONFIRM_STATE,
	B.FPRODUCT_TYPE,
	(SELECT C.FNAME FROM T_BUDGET_CENTER AS C WITH(NOLOCK) WHERE C.FID=B.FBUDGETCENTERID) AS FBUDGET_CENTER_NAME,
	(SELECT I.FNAME FROM T_BUDGET_ITEM AS I WITH(NOLOCK) WHERE I.FID=B.FBUDGETITEMID) AS FBUDGET_ITEM_NAME,
(SELECT ASSITEM.FNAME FROM T_BUDGET_ASSISTANT_ITEM AS ASSITEM WITH(NOLOCK) WHERE ASSITEM.FID=B.FASSISTANT_ITEM_ID) AS FBUDGET_ASSISTANT_NAME,
	G.FNAME+CAST(V.FNUMBER AS VARCHAR(200)) AS FKINGDEE_VOUCHER_CODE,
	B.FCHECK,
	P.FROW,
	P.FPRODUCT_TYPE AS FPRODUCT_TYPE_TOP,
	P.FPRODUCT_TYPE_ID,
	CASE P.FPRODUCT_TYPE
	WHEN ''TOP'' THEN (SELECT T.FNAME FROM T_BATCHNO_PRODTYPE AS T WITH(NOLOCK) WHERE T.FID=P.FPRODUCT_TYPE_ID)
	WHEN ''CHILDREN'' THEN (SELECT C.FONENAME+'' - ''+C.FTWONAME FROM T_BATCHNO_CLASS AS C WITH(NOLOCK) WHERE C.FID=P.FPRODUCT_TYPE_ID)
	END AS FPRODUCT_TYPE_NAME,
	P.FRATE,
	P.FMATERIAL_ID,
	(SELECT M1.FMATERIALNO FROM T_MATERIAL AS M1 WITH(NOLOCK) WHERE M1.FMATERIALID=P.FMATERIAL_ID) AS FMATERIAL_NO,
	(SELECT M2.FMATERIALNAME FROM T_MATERIAL AS M2 WITH(NOLOCK) WHERE M2.FMATERIALID=P.FMATERIAL_ID) AS FMATERIAL_NAME,
	P.FSELL_YEAR
	FROM T_BT AS B WITH(NOLOCK)
	INNER JOIN T_BT_P AS P WITH(NOLOCK) ON P.FID=B.FID
	LEFT JOIN T_FI_ACCDOC AS F WITH(NOLOCK) ON F.FACCTDOCID=B.FACCDOCID
	LEFT JOIN OPENROWSET(''SQLOLEDB'','''+@LS_SERVER+''';'''+@LS_USER+'''; '''+@LS_PASSWORD+''', '+@LS_DATABASE+'.DBO.T_VOUCHER) V ON V.FSERIALNUM=F.FK3SERIALNUMBER
	LEFT JOIN OPENROWSET(''SQLOLEDB'','''+@LS_SERVER+''';'''+@LS_USER+''';'''+@LS_PASSWORD+''', '+@LS_DATABASE+'.DBO.T_VOUCHERGROUP) G ON G.FGROUPID=V.FGROUPID
	'
	
END

EXEC(@LS_SQL)

End
