
-- =============================================
-- AUTHOR: 郭凯斌
-- CREATE DATE: 2013-11-07
-- DESCRIPTION: 预算方案生成报表
-- =============================================

Create  Procedure P_Budget_Form_Generate(
@LS_BUDGET_CASE_ID VARCHAR(200),
@LI_USER_ID INT
)
AS

BEGIN

DECLARE @LI_BUDGET_CASE_ID INT
DECLARE @LI_BUDGET_MODEL_ID INT,@LS_BUDGET_MODEL_NO VARCHAR(200),@LS_BUDGET_MODEL_NAME VARCHAR(200)
DECLARE @LI_BUDGET_CENTER_ID INT,@LS_BUDGET_CENTER_NO VARCHAR(200),@LS_BUDGET_CENTER_NAME VARCHAR(200)
DECLARE @LI_BUDGET_FORM_ID INT,@LD_START_DATE DATETIME,@LD_END_DATE DATETIME,@LS_BUDGET_FORM_NAME VARCHAR(200),@LS_BUDGET_FORM_NO VARCHAR(200)
DECLARE @LI_BUDGET_ITEM_ID INT,@LS_COLUMN VARCHAR(200),@LI_VALUE_TYPE TINYINT,@LI_TYPE TINYINT,@LS_VALUE_FORMULA VARCHAR(4000),@LD_VALUE MONEY
DECLARE @LI_ROW INT
DECLARE @LS_START_DATE CHAR(10),@LS_END_DATE CHAR(10),@LI_YEAR SMALLINT,@LI_MONTH TINYINT,@LS_YEAR CHAR(4),@LS_MONTH CHAR(2),@LS_SEASON CHAR(2)
DECLARE @LS_ACCOUNT_YEAR1 CHAR(4),@LS_ACCOUNT_YEAR2 CHAR(4),@LS_ACCOUNT_MONTH1 CHAR(2),@LS_ACCOUNT_MONTH2 CHAR(2)
DECLARE @N INT,@C INT,@LI_COLUMN INT,@LS_EXPRESSION VARCHAR(4000),@LS_VALUE_FORMULA_ORIGINAL VARCHAR(4000)
DECLARE @LI_TIME TINYINT,@LS_TIME VARCHAR(200),@LS_NAME VARCHAR(200),@LS_COLUMN_HISTORY VARCHAR(200),@LS_SQL NVARCHAR(200)
DECLARE @LI_PARENT_BUDGET_ITEM_ID INT
DECLARE @LI_YEAR_TARGET BIT,@LD_YEAR_TARGET_START_DATE DATETIME,@LD_YEAR_TARGET_END_DATE DATETIME

IF NOT RIGHT(@LS_BUDGET_CASE_ID,1)=','
	SET @LS_BUDGET_CASE_ID=@LS_BUDGET_CASE_ID+','

WHILE CHARINDEX(',',@LS_BUDGET_CASE_ID)>0
BEGIN
	
	SET @LI_BUDGET_CASE_ID=CONVERT(INT,LEFT(@LS_BUDGET_CASE_ID,CHARINDEX(',',@LS_BUDGET_CASE_ID) -1))
	
	DECLARE LDS_FORM_HEADER CURSOR FOR
	SELECT
	D.FBUDGET_MODEL_ID,
	(SELECT M1.FNO FROM T_BUDGET_MODEL_HEADER AS M1 WITH(NOLOCK) WHERE M1.FID=D.FBUDGET_MODEL_ID),
	(SELECT M2.FNAME FROM T_BUDGET_MODEL_HEADER AS M2 WITH(NOLOCK) WHERE M2.FID=D.FBUDGET_MODEL_ID),
	C.FBUDGET_CENTER_ID,
	(SELECT C1.FNO FROM T_BUDGET_CENTER AS C1 WITH(NOLOCK) WHERE C1.FID=C.FBUDGET_CENTER_ID),
	(SELECT C2.FNAME FROM T_BUDGET_CENTER AS C2 WITH(NOLOCK) WHERE C2.FID=C.FBUDGET_CENTER_ID),
	(SELECT H1.FSTART_DATE FROM T_BUDGET_CASE_HEADER AS H1 WITH(NOLOCK) WHERE H1.FID=D.FID),
	(SELECT H2.FEND_DATE FROM T_BUDGET_CASE_HEADER AS H2 WITH(NOLOCK) WHERE H2.FID=D.FID),
	H.FYEAR_TARGET,
	H.FYEAR_TARGET_START_DATE,
	H.FYEAR_TARGET_END_DATE
	FROM T_BUDGET_CASE_CENTER AS C WITH(NOLOCK)
	LEFT JOIN T_BUDGET_CASE_DETAIL AS D WITH(NOLOCK) ON C.FBUDGET_CASE_ID=D.FID
	INNER JOIN T_BUDGET_CASE_HEADER AS H WITH(NOLOCK) ON H.FID=D.FID
	WHERE C.FBUDGET_CASE_ID=@LI_BUDGET_CASE_ID
	ORDER BY C.FBUDGET_CASE_ID,C.FBUDGET_CENTER_ID,D.FBUDGET_MODEL_ID
	
	OPEN LDS_FORM_HEADER
	
	FETCH NEXT FROM LDS_FORM_HEADER
	INTO @LI_BUDGET_MODEL_ID,@LS_BUDGET_MODEL_NO,@LS_BUDGET_MODEL_NAME,
	@LI_BUDGET_CENTER_ID,@LS_BUDGET_CENTER_NO,@LS_BUDGET_CENTER_NAME,
	@LD_START_DATE,@LD_END_DATE,@LI_YEAR_TARGET,@LD_YEAR_TARGET_START_DATE,@LD_YEAR_TARGET_END_DATE
	
	WHILE @@FETCH_STATUS=0
	BEGIN
		IF EXISTS(SELECT * FROM T_TABLEID WITH(NOLOCK) WHERE FTABLE='T_BUDGET_FORM_HEADER')
		BEGIN
			SET @LI_BUDGET_FORM_ID=(SELECT ISNULL(FCURRID,1000)+1 FROM T_TABLEID WITH(NOLOCK) WHERE FTABLE='T_BUDGET_FORM_HEADER')
			UPDATE T_TABLEID SET FCURRID=@LI_BUDGET_FORM_ID WHERE FTABLE='T_BUDGET_FORM_HEADER'
		END
		ELSE
		BEGIN
			INSERT INTO T_TABLEID VALUES('T_BUDGET_FORM_HEADER',1000)
			SET @LI_BUDGET_FORM_ID=1000
		END
		
		SET @LS_START_DATE=CONVERT(CHAR(10),@LD_START_DATE,20)
		SET @LS_END_DATE=CONVERT(CHAR(10),@LD_END_DATE,20)
		
		SET @LS_BUDGET_FORM_NAME=@LS_BUDGET_MODEL_NAME
		SET @LS_BUDGET_FORM_NO=REPLACE(CONVERT(CHAR(10),GETDATE(),20),'-','')+CONVERT(VARCHAR(10),@LI_BUDGET_FORM_ID)
		
		INSERT INTO T_BUDGET_FORM_HEADER(FID,FNO,FNAME,FREMARK,FBUDGET_CENTER_ID,FSTATE,FCREATE_ID,FCREATE_DATE,FSTART_DATE,FEND_DATE,FLEVEL,FCONFIRM_ID,FCONFIRM_DATE,FYEAR_TARGET,FYEAR_TARGET_START_DATE,FYEAR_TARGET_END_DATE,FCONFIRM_STATE)
		VALUES(
		@LI_BUDGET_FORM_ID,
		@LS_BUDGET_FORM_NO,
		@LS_BUDGET_FORM_NAME,
		NULL,
		@LI_BUDGET_CENTER_ID,
		0,
		@LI_USER_ID,
		GETDATE(),
		@LD_START_DATE,
		@LD_END_DATE,
		0,
		NULL,
		NULL,
		@LI_YEAR_TARGET,
		@LD_YEAR_TARGET_START_DATE,
		@LD_YEAR_TARGET_END_DATE,
		0)
		
		IF NOT @@ERROR=0
		BEGIN
	
			CLOSE LDS_FORM_HEADER
			DEALLOCATE LDS_FORM_HEADER
			RETURN
		END
		
		INSERT INTO T_BUDGET_FORM_DETAIL(FID,FROW,FBUDGET_ITEM_ID,FVALUE_TYPE,FVALUE_FORMULA,FTYPE,FTIME,FFORMULA,FREMARK,FYEAR_TARGET)
		SELECT
		@LI_BUDGET_FORM_ID,
		M.FROW,
		M.FBUDGET_ITEM_ID,
		M.FVALUE_TYPE,
		M.FVALUE_FORMULA,
		I.FTYPE,
		I.FTIME,
		I.FFORMULA,
		NULL,
		ISNULL((SELECT CI.FYEAR_TARGET FROM T_BUDGET_CASE_ITEM AS CI WITH(NOLOCK) WHERE CI.FID=@LI_BUDGET_CASE_ID AND CI.FBUDGET_ITEM_ID=M.FBUDGET_ITEM_ID),0)
		FROM T_BUDGET_MODEL_DETAIL AS M WITH(NOLOCK)
		INNER JOIN T_BUDGET_CENTER_ITEM AS I WITH(NOLOCK)
		ON I.FBUDGET_ITEM_ID=M.FBUDGET_ITEM_ID
		WHERE M.FID=@LI_BUDGET_MODEL_ID AND I.FBUDGET_CENTER_ID=@LI_BUDGET_CENTER_ID
		AND NOT EXISTS (SELECT * FROM T_BUDGET_FORM_DETAIL AS F1 WITH(NOLOCK) INNER JOIN T_BUDGET_FORM_HEADER AS F2 WITH(NOLOCK)
		ON F1.FID=F2.FID
		WHERE F2.FBUDGET_CENTER_ID=@LI_BUDGET_CENTER_ID
		AND F1.FBUDGET_ITEM_ID=M.FBUDGET_ITEM_ID
		AND CONVERT(VARCHAR(10),F2.FSTART_DATE,20)<=CONVERT(VARCHAR(10),@LD_END_DATE,20) AND CONVERT(VARCHAR(10),F2.FEND_DATE,20)>=CONVERT(VARCHAR(10),@LD_START_DATE,20))
		
		IF NOT @@ERROR=0
		BEGIN
			CLOSE LDS_FORM_HEADER
			DEALLOCATE LDS_FORM_HEADER
			RETURN
		END
		
		INSERT INTO T_BUDGET_FORM_DETAIL(FID,FROW,FBUDGET_ITEM_ID,FVALUE_TYPE,FVALUE_FORMULA,FTYPE,FTIME,FFORMULA,FREMARK,FYEAR_TARGET)
		SELECT
		@LI_BUDGET_FORM_ID,
		M.FROW,
		M.FBUDGET_ITEM_ID,
		M.FVALUE_TYPE,
		M.FVALUE_FORMULA,
		I.FTYPE,
		I.FTIME,
		NULL,
		NULL,
		ISNULL((SELECT CI.FYEAR_TARGET FROM T_BUDGET_CASE_ITEM AS CI WITH(NOLOCK) WHERE CI.FID=@LI_BUDGET_CASE_ID AND CI.FBUDGET_ITEM_ID=M.FBUDGET_ITEM_ID),0)
		FROM T_BUDGET_MODEL_DETAIL AS M WITH(NOLOCK)
		INNER JOIN T_BUDGET_ITEM AS I WITH(NOLOCK)
		ON I.FID=M.FBUDGET_ITEM_ID
		WHERE M.FID=@LI_BUDGET_MODEL_ID AND I.FID NOT IN (SELECT CI.FBUDGET_ITEM_ID FROM T_BUDGET_CENTER_ITEM AS CI WITH(NOLOCK) WHERE CI.FBUDGET_CENTER_ID=@LI_BUDGET_CENTER_ID)
		AND NOT EXISTS (SELECT * FROM T_BUDGET_FORM_DETAIL AS F1 WITH(NOLOCK) INNER JOIN T_BUDGET_FORM_HEADER AS F2 WITH(NOLOCK)
		ON F1.FID=F2.FID
		WHERE F2.FBUDGET_CENTER_ID=@LI_BUDGET_CENTER_ID
		AND F1.FBUDGET_ITEM_ID=M.FBUDGET_ITEM_ID
		AND CONVERT(VARCHAR(10),F2.FSTART_DATE,20)<=CONVERT(VARCHAR(10),@LD_END_DATE,20) AND CONVERT(VARCHAR(10),F2.FEND_DATE,20)>=CONVERT(VARCHAR(10),@LD_START_DATE,20))
		
		IF NOT @@ERROR=0
		BEGIN
			CLOSE LDS_FORM_HEADER
			DEALLOCATE LDS_FORM_HEADER
			RETURN
		END
		
		IF NOT EXISTS(SELECT * FROM T_BUDGET_FORM_DETAIL WITH(NOLOCK) WHERE FID=@LI_BUDGET_FORM_ID)
		BEGIN
			DELETE T_BUDGET_FORM_HEADER WHERE FID=@LI_BUDGET_FORM_ID
			
			FETCH NEXT FROM LDS_FORM_HEADER
			INTO @LI_BUDGET_MODEL_ID,@LS_BUDGET_MODEL_NO,@LS_BUDGET_MODEL_NAME,
			@LI_BUDGET_CENTER_ID,@LS_BUDGET_CENTER_NO,@LS_BUDGET_CENTER_NAME,
			@LD_START_DATE,@LD_END_DATE
			
			CONTINUE
		END
		
		SET @LI_BUDGET_ITEM_ID=(SELECT D.FBUDGET_ITEM_ID FROM T_BUDGET_FORM_DETAIL AS D WITH(NOLOCK) WHERE D.FID=@LI_BUDGET_FORM_ID
		AND D.FROW=(SELECT MIN(D2.FROW) FROM T_BUDGET_FORM_DETAIL AS D2 WITH(NOLOCK) WHERE D2.FID=@LI_BUDGET_FORM_ID))
		SET @LI_VALUE_TYPE=(SELECT D.FVALUE_TYPE FROM T_BUDGET_FORM_DETAIL AS D WITH(NOLOCK) WHERE D.FID=@LI_BUDGET_FORM_ID
		AND D.FROW=(SELECT MIN(D2.FROW) FROM T_BUDGET_FORM_DETAIL AS D2 WITH(NOLOCK) WHERE D2.FID=@LI_BUDGET_FORM_ID))
		
		SET @LI_ROW=0
		SET @LS_ACCOUNT_YEAR1=NULL
		SET @LS_ACCOUNT_YEAR2=NULL
		SET @LS_ACCOUNT_MONTH1=NULL
		SET @LS_ACCOUNT_MONTH2=NULL
	
		WHILE @LS_START_DATE<=@LS_END_DATE
		BEGIN
			
			SET @LS_ACCOUNT_YEAR1=(SELECT CONVERT(CHAR(4),FYEAR) FROM T_ACCOUNTPERIOD WITH(NOLOCK)
			WHERE CONVERT(CHAR(10),FBEGDATE,20)<=@LS_START_DATE AND CONVERT(CHAR(10),FENDDATE,20)>=@LS_START_DATE)
			SET @LS_ACCOUNT_MONTH1=(SELECT CONVERT(VARCHAR(2),FPERIOD) FROM T_ACCOUNTPERIOD WITH(NOLOCK)
			WHERE CONVERT(CHAR(10),FBEGDATE,20)<=@LS_START_DATE AND CONVERT(CHAR(10),FENDDATE,20)>=@LS_START_DATE)
			
			IF NOT LEN(@LS_ACCOUNT_YEAR1)>0 OR @LS_ACCOUNT_YEAR1 IS NULL OR NOT LEN(@LS_ACCOUNT_MONTH1)>0 OR @LS_ACCOUNT_MONTH1 IS NULL
			BEGIN
				DELETE T_BUDGET_FORM_VALUE WHERE FID=@LI_BUDGET_FORM_ID
				
				BREAK
			END
			
			IF NOT LEN(@LS_ACCOUNT_YEAR2)>0 OR @LS_ACCOUNT_YEAR2 IS NULL OR NOT @LS_ACCOUNT_YEAR1=@LS_ACCOUNT_YEAR2
			BEGIN
				SET @LI_ROW=@LI_ROW+1
				SET @LS_COLUMN='AY000000'+@LS_ACCOUNT_YEAR1+'00'
				INSERT INTO T_BUDGET_FORM_VALUE(FID,FROW,FCOLUMN,FVALUE,FBUDGET_ITEM_ID)
				VALUES(@LI_BUDGET_FORM_ID,@LI_ROW,@LS_COLUMN,NULL,@LI_BUDGET_ITEM_ID)
				
				SET @LI_ROW=@LI_ROW+1
				SET @LS_COLUMN='BY000000'+@LS_ACCOUNT_YEAR1+'00'
				INSERT INTO T_BUDGET_FORM_VALUE(FID,FROW,FCOLUMN,FVALUE,FBUDGET_ITEM_ID)
				VALUES(@LI_BUDGET_FORM_ID,@LI_ROW,@LS_COLUMN,NULL,@LI_BUDGET_ITEM_ID)
			END
			
			SET @LS_YEAR=LEFT(@LS_START_DATE,4)
			SET @LS_MONTH=SUBSTRING(@LS_START_DATE,6,2)
			SET @LI_YEAR=CONVERT(SMALLINT,@LS_YEAR)
			SET @LI_MONTH=CONVERT(TINYINT,@LS_MONTH)
			IF LEN(@LS_ACCOUNT_MONTH1)=1
				SET @LS_ACCOUNT_MONTH1='0'+@LS_ACCOUNT_MONTH1
			
			SET @LI_ROW=@LI_ROW+1
			SET @LS_COLUMN='AM'+@LS_YEAR+@LS_MONTH+@LS_ACCOUNT_YEAR1+@LS_ACCOUNT_MONTH1
			INSERT INTO T_BUDGET_FORM_VALUE(FID,FROW,FCOLUMN,FVALUE,FBUDGET_ITEM_ID)
			VALUES(@LI_BUDGET_FORM_ID,@LI_ROW,@LS_COLUMN,NULL,@LI_BUDGET_ITEM_ID)
			
			SET @LI_ROW=@LI_ROW+1
			SET @LS_COLUMN='BM'+@LS_YEAR+@LS_MONTH+@LS_ACCOUNT_YEAR1+@LS_ACCOUNT_MONTH1
			INSERT INTO T_BUDGET_FORM_VALUE(FID,FROW,FCOLUMN,FVALUE,FBUDGET_ITEM_ID)
			VALUES(@LI_BUDGET_FORM_ID,@LI_ROW,@LS_COLUMN,NULL,@LI_BUDGET_ITEM_ID)
			
			IF @LS_ACCOUNT_MONTH1>='01' AND @LS_ACCOUNT_MONTH1<='03'
				SET @LS_SEASON='01'
			ELSE IF @LS_ACCOUNT_MONTH1>='04' AND @LS_ACCOUNT_MONTH1<='06'
				SET @LS_SEASON='02'
			ELSE IF @LS_ACCOUNT_MONTH1>='07' AND @LS_ACCOUNT_MONTH1<='09'
				SET @LS_SEASON='03'
			ELSE IF @LS_ACCOUNT_MONTH1>='10' AND @LS_ACCOUNT_MONTH1<='12'
				SET @LS_SEASON='04'
			
			IF @LS_ACCOUNT_MONTH1 IN ('03','06','09','12') OR LEFT(@LS_START_DATE,7)=LEFT(@LS_END_DATE,7)
			BEGIN
				SET @LI_ROW=@LI_ROW+1
				SET @LS_COLUMN='AS000000'+@LS_ACCOUNT_YEAR1+@LS_SEASON
				INSERT INTO T_BUDGET_FORM_VALUE(FID,FROW,FCOLUMN,FVALUE,FBUDGET_ITEM_ID)
				VALUES(@LI_BUDGET_FORM_ID,@LI_ROW,@LS_COLUMN,NULL,@LI_BUDGET_ITEM_ID)
				
				SET @LI_ROW=@LI_ROW+1
				SET @LS_COLUMN='BS000000'+@LS_ACCOUNT_YEAR1+@LS_SEASON
	
				INSERT INTO T_BUDGET_FORM_VALUE(FID,FROW,FCOLUMN,FVALUE,FBUDGET_ITEM_ID)
				VALUES(@LI_BUDGET_FORM_ID,@LI_ROW,@LS_COLUMN,NULL,@LI_BUDGET_ITEM_ID)
			END
			
			IF @LI_MONTH+1>12
			BEGIN
				SET @LI_YEAR=@LI_YEAR+1
				SET @LI_MONTH=1
			END
			ELSE
				SET @LI_MONTH=@LI_MONTH+1
			
			IF @LI_MONTH>=10
				SET @LS_START_DATE=CAST(@LI_YEAR AS CHAR(4))+'-'+CAST(@LI_MONTH AS CHAR(2))+'-01'
			ELSE
				SET @LS_START_DATE=CAST(@LI_YEAR AS CHAR(4))+'-0'+CAST(@LI_MONTH AS CHAR(1))+'-01'
			
			SET @LS_ACCOUNT_YEAR2=@LS_ACCOUNT_YEAR1
			SET @LS_ACCOUNT_MONTH2=@LS_ACCOUNT_MONTH1
		END
		
		IF NOT EXISTS(SELECT * FROM T_BUDGET_FORM_VALUE WITH(NOLOCK) WHERE FID=@LI_BUDGET_FORM_ID)
		BEGIN
			DELETE T_BUDGET_FORM_HEADER WHERE FID=@LI_BUDGET_FORM_ID
			DELETE T_BUDGET_FORM_DETAIL WHERE FID=@LI_BUDGET_FORM_ID
			
			FETCH NEXT FROM LDS_FORM_HEADER
			INTO @LI_BUDGET_MODEL_ID,@LS_BUDGET_MODEL_NO,@LS_BUDGET_MODEL_NAME,
			@LI_BUDGET_CENTER_ID,@LS_BUDGET_CENTER_NO,@LS_BUDGET_CENTER_NAME,
			@LD_START_DATE,@LD_END_DATE
			
			CONTINUE
		END
		
		INSERT INTO T_BUDGET_FORM_VALUE(FID,FROW,FCOLUMN,FVALUE,FBUDGET_ITEM_ID)
		SELECT
		@LI_BUDGET_FORM_ID,
		V.FROW,
		V.FCOLUMN,
		V.FVALUE,
		D.FBUDGET_ITEM_ID
		FROM T_BUDGET_FORM_DETAIL AS D WITH(NOLOCK) LEFT JOIN T_BUDGET_FORM_VALUE AS V WITH(NOLOCK)
		ON D.FID=V.FID
		WHERE NOT D.FBUDGET_ITEM_ID=@LI_BUDGET_ITEM_ID AND D.FID=@LI_BUDGET_FORM_ID
		
		IF NOT @@ERROR=0
		BEGIN
			CLOSE LDS_FORM_HEADER
			DEALLOCATE LDS_FORM_HEADER
			RETURN
		END
		
		INSERT INTO T_BUDGET_FORM_ELEMENT(FID,FBUDGET_ITEM_ID,FCOLUMN,FNAME,FROW,FVALUE,FREMARK)
		SELECT
		@LI_BUDGET_FORM_ID,
		D.FBUDGET_ITEM_ID,
		V.FCOLUMN,
		M.FNAME,
		M.FROW,
		NULL,
		M.FREMARK
		FROM T_BUDGET_FORM_VALUE AS V WITH(NOLOCK) INNER JOIN
		T_BUDGET_FORM_DETAIL AS D WITH(NOLOCK) ON V.FID=D.FID AND V.FBUDGET_ITEM_ID=D.FBUDGET_ITEM_ID INNER JOIN
		T_BUDGET_FORM_HEADER AS H WITH(NOLOCK) ON D.FID=H.FID INNER JOIN
		T_BUDGET_MODEL_ELEMENT AS M WITH(NOLOCK) ON M.FBUDGET_ITEM_ID=D.FBUDGET_ITEM_ID
		WHERE V.FID=@LI_BUDGET_FORM_ID AND D.FVALUE_TYPE=2 AND M.FID=@LI_BUDGET_MODEL_ID
		
		IF NOT @@ERROR=0
		BEGIN
			CLOSE LDS_FORM_HEADER
			DEALLOCATE LDS_FORM_HEADER
			RETURN
		END
		
		DECLARE LDS_FORM_DETAIL CURSOR FOR
		SELECT
		D.FBUDGET_ITEM_ID,
		D.FVALUE_TYPE,
		D.FTIME,
		CONVERT(VARCHAR(4000),D.FVALUE_FORMULA),
		(SELECT COUNT(*) FROM T_BUDGET_FORM_VALUE AS V WITH(NOLOCK) WHERE V.FID=@LI_BUDGET_FORM_ID AND V.FBUDGET_ITEM_ID=D.FBUDGET_ITEM_ID)
		FROM T_BUDGET_FORM_DETAIL AS D WITH(NOLOCK) WHERE D.FID=@LI_BUDGET_FORM_ID
		AND D.FVALUE_TYPE=3
		ORDER BY D.FROW
		
		OPEN LDS_FORM_DETAIL
		
		FETCH NEXT FROM LDS_FORM_DETAIL
		INTO @LI_BUDGET_ITEM_ID,@LI_VALUE_TYPE,@LI_TIME,@LS_VALUE_FORMULA_ORIGINAL,@LI_COLUMN
		
		WHILE @@FETCH_STATUS=0
		BEGIN
			
			IF @LI_TIME=0
				SET @LS_TIME='Y'
			IF @LI_TIME=1
				SET @LS_TIME='S'
			IF @LI_TIME=2
				SET @LS_TIME='M'
			
			DECLARE LDS_FORM_VALUE CURSOR FOR
			SELECT
			FCOLUMN
			FROM T_BUDGET_FORM_VALUE WITH(NOLOCK)
			WHERE FID=@LI_BUDGET_FORM_ID AND FBUDGET_ITEM_ID=@LI_BUDGET_ITEM_ID AND SUBSTRING(FCOLUMN,2,1)=@LS_TIME
			ORDER BY FROW
			
			OPEN LDS_FORM_VALUE
			
			FETCH NEXT FROM LDS_FORM_VALUE
			INTO @LS_COLUMN
			
			WHILE @@FETCH_STATUS=0
			BEGIN
				SET @LS_VALUE_FORMULA=@LS_VALUE_FORMULA_ORIGINAL
				SET @LS_EXPRESSION=@LS_VALUE_FORMULA_ORIGINAL
				SET @LS_SQL=NULL
				
				SET @N=CHARINDEX('[',@LS_VALUE_FORMULA)
				
				WHILE @N>0 AND NOT @N IS NULL
				BEGIN
					SET @C=CHARINDEX(']',@LS_VALUE_FORMULA,@N)
					
					IF @C>0 AND NOT @C IS NULL
					BEGIN
						SET @LS_NAME=SUBSTRING(@LS_VALUE_FORMULA,@N,@C - @N + 1)
						
						SET @LD_VALUE=NULL
						SET @LS_START_DATE=NULL
						SET @LS_END_DATE=NULL
						
						IF @LI_TIME=0
						BEGIN
							SET @LS_START_DATE=(SELECT CONVERT(VARCHAR(20),MIN(FBEGDATE),20) FROM T_ACCOUNTPERIOD WITH(NOLOCK)
							WHERE CONVERT(VARCHAR(4),FYEAR)=SUBSTRING(@LS_NAME,2,4))
							
							SET @LS_END_DATE=(SELECT CONVERT(VARCHAR(20),MAX(FENDDATE),20) FROM T_ACCOUNTPERIOD WITH(NOLOCK)
							WHERE CONVERT(VARCHAR(4),FYEAR)=SUBSTRING(@LS_NAME,2,4))
						END
						IF @LI_TIME=1
						BEGIN
							IF RIGHT(@LS_COLUMN,2)='01'
							BEGIN
								SET @LS_START_DATE=(SELECT CONVERT(VARCHAR(20),MIN(FBEGDATE),20) FROM T_ACCOUNTPERIOD WITH(NOLOCK)
								WHERE CONVERT(VARCHAR(4),FYEAR)=SUBSTRING(@LS_NAME,2,4)
								AND CONVERT(VARCHAR(2),FPERIOD) IN ('1','2','3'))
								
								SET @LS_END_DATE=(SELECT CONVERT(VARCHAR(20),MAX(FENDDATE),20) FROM T_ACCOUNTPERIOD WITH(NOLOCK)
								WHERE CONVERT(VARCHAR(4),FYEAR)=SUBSTRING(@LS_NAME,2,4)
								AND CONVERT(VARCHAR(2),FPERIOD) IN ('1','2','3'))
							END
							IF RIGHT(@LS_COLUMN,2)='02'
							BEGIN
								SET @LS_START_DATE=(SELECT CONVERT(VARCHAR(20),MIN(FBEGDATE),20) FROM T_ACCOUNTPERIOD WITH(NOLOCK)
								WHERE CONVERT(VARCHAR(4),FYEAR)=SUBSTRING(@LS_NAME,2,4)
								AND CONVERT(VARCHAR(2),FPERIOD) IN ('4','5','6'))
								
								SET @LS_END_DATE=(SELECT CONVERT(VARCHAR(20),MAX(FENDDATE),20) FROM T_ACCOUNTPERIOD WITH(NOLOCK)
								WHERE CONVERT(VARCHAR(4),FYEAR)=SUBSTRING(@LS_NAME,2,4)
								AND CONVERT(VARCHAR(2),FPERIOD) IN ('4','5','6'))
							END
							IF RIGHT(@LS_COLUMN,2)='03'
							BEGIN								SET @LS_START_DATE=(SELECT CONVERT(VARCHAR(20),MIN(FBEGDATE),20) FROM T_ACCOUNTPERIOD WITH(NOLOCK)
								WHERE CONVERT(VARCHAR(4),FYEAR)=SUBSTRING(@LS_NAME,2,4)
								AND CONVERT(VARCHAR(2),FPERIOD) IN ('7','8','9'))
								
								SET @LS_END_DATE=(SELECT CONVERT(VARCHAR(20),MAX(FENDDATE),20) FROM T_ACCOUNTPERIOD WITH(NOLOCK)
								WHERE CONVERT(VARCHAR(4),FYEAR)=SUBSTRING(@LS_NAME,2,4)
								AND CONVERT(VARCHAR(2),FPERIOD) IN ('7','8','9'))
							END
							IF RIGHT(@LS_COLUMN,2)='04'
							BEGIN
								SET @LS_START_DATE=(SELECT CONVERT(VARCHAR(20),MIN(FBEGDATE),20) FROM T_ACCOUNTPERIOD WITH(NOLOCK)
								WHERE CONVERT(VARCHAR(4),FYEAR)=SUBSTRING(@LS_NAME,2,4)
								AND CONVERT(VARCHAR(2),FPERIOD) IN ('10','11','12'))
								
								SET @LS_END_DATE=(SELECT CONVERT(VARCHAR(20),MAX(FENDDATE),20) FROM T_ACCOUNTPERIOD WITH(NOLOCK)
								WHERE CONVERT(VARCHAR(4),FYEAR)=SUBSTRING(@LS_NAME,2,4)
								AND CONVERT(VARCHAR(2),FPERIOD) IN ('10','11','12'))
							END
						END
						IF @LI_TIME=2
						BEGIN
							SET @LS_START_DATE=(SELECT CONVERT(VARCHAR(20),MIN(FBEGDATE),20) FROM T_ACCOUNTPERIOD WITH(NOLOCK)
							WHERE CONVERT(VARCHAR(4),FYEAR)=SUBSTRING(@LS_NAME,2,4)
							AND CONVERT(VARCHAR(2),FPERIOD)=RIGHT(@LS_COLUMN,2))
							
							SET @LS_END_DATE=(SELECT CONVERT(VARCHAR(20),MAX(FENDDATE),20) FROM T_ACCOUNTPERIOD WITH(NOLOCK)
							WHERE CONVERT(VARCHAR(4),FYEAR)=SUBSTRING(@LS_NAME,2,4)
							AND CONVERT(VARCHAR(2),FPERIOD)=RIGHT(@LS_COLUMN,2))
						END
						
						IF SUBSTRING(@LS_NAME,9,2)='预算'
						BEGIN
							SET @LS_COLUMN_HISTORY=LEFT(@LS_COLUMN,8)+SUBSTRING(@LS_NAME,2,4)+RIGHT(@LS_COLUMN,2)
							
							SET @LD_VALUE=ISNULL((SELECT TOP 1 V.FVALUE FROM T_BUDGET_FORM_VALUE AS V WITH(NOLOCK) INNER JOIN
							T_BUDGET_FORM_DETAIL AS D WITH(NOLOCK) ON V.FID=D.FID INNER JOIN
							T_BUDGET_FORM_HEADER AS H WITH(NOLOCK) ON V.FID=H.FID
							WHERE H.FBUDGET_CENTER_ID=@LI_BUDGET_CENTER_ID AND V.FBUDGET_ITEM_ID=@LI_BUDGET_ITEM_ID
							AND V.FCOLUMN=@LS_COLUMN_HISTORY AND H.FSTATE=2 ORDER BY H.FSTART_DATE DESC),0)
							
						END
						IF SUBSTRING(@LS_NAME,9,2)='下拨'
						BEGIN
							SET @LD_VALUE=ISNULL((SELECT SUM(D.FVALUE) FROM T_BUDGET_ALLOCATE_DETAIL AS D WITH(NOLOCK) INNER JOIN
							T_BUDGET_ALLOCATE_HEADER AS H WITH(NOLOCK) ON D.FID=H.FID
							WHERE H.FVALUE_BUDGET_CENTER_ID=@LI_BUDGET_CENTER_ID AND
							CONVERT(VARCHAR(10),H.FDATE,20)>=@LS_START_DATE AND
							CONVERT(VARCHAR(10),H.FDATE,20)<=@LS_END_DATE AND H.FSTATE=2),0)
							
						END
						IF SUBSTRING(@LS_NAME,9,2)='报账'
						BEGIN
							SET @LD_VALUE=ISNULL((SELECT SUM(D.FAMOUNT) FROM T_BUDGET_REPORT_DETAIL AS D WITH(NOLOCK) INNER JOIN
							T_BUDGET_REPORT_HEADER AS H WITH(NOLOCK) ON D.FID=H.FID
							WHERE H.FVALUE_BUDGET_CENTER_ID=@LI_BUDGET_CENTER_ID AND
							CONVERT(VARCHAR(10),H.FDATE,20)>=@LS_START_DATE AND
							CONVERT(VARCHAR(10),H.FDATE,20)<=@LS_END_DATE AND H.FSTATE=2),0)
							
						END
						
						IF @LD_VALUE IS NULL
							SET @LD_VALUE=0
						
						SET @LS_EXPRESSION=REPLACE(@LS_EXPRESSION,@LS_NAME,CONVERT(VARCHAR(200),@LD_VALUE))
						
					END
						
					SET @LS_VALUE_FORMULA=RIGHT(@LS_VALUE_FORMULA,LEN(@LS_VALUE_FORMULA) - @C)
					
					SET @N=CHARINDEX('[',@LS_VALUE_FORMULA)
				END
				
				SET @LS_SQL='UPDATE T_BUDGET_FORM_VALUE SET FVALUE='+@LS_EXPRESSION+' 
				WHERE FID='+CONVERT(VARCHAR(200),@LI_BUDGET_FORM_ID)+' AND FBUDGET_ITEM_ID='+CONVERT(VARCHAR(200),@LI_BUDGET_ITEM_ID)+' AND FCOLUMN='''+@LS_COLUMN+''''
				
				EXECUTE DBO.SP_EXECUTESQL @LS_SQL
				
				FETCH NEXT FROM LDS_FORM_VALUE
				INTO @LS_COLUMN
			END
			
			CLOSE LDS_FORM_VALUE
			DEALLOCATE LDS_FORM_VALUE
			
			DECLARE LDS_FORM_VALUE CURSOR FOR
			SELECT
			FCOLUMN,
			ISNULL(FVALUE,0)
			FROM T_BUDGET_FORM_VALUE WITH(NOLOCK)
			WHERE FID=@LI_BUDGET_FORM_ID AND FBUDGET_ITEM_ID=@LI_BUDGET_ITEM_ID AND SUBSTRING(FCOLUMN,2,1)=@LS_TIME
			AND FVALUE>0 AND NOT FVALUE IS NULL
			ORDER BY FROW
			
			OPEN LDS_FORM_VALUE
			
			FETCH NEXT FROM LDS_FORM_VALUE
			INTO @LS_COLUMN,@LD_VALUE
			
			WHILE @@FETCH_STATUS=0
			BEGIN
				
				SET @LS_TIME=SUBSTRING(@LS_COLUMN,2,1)
				SET @LS_MONTH=RIGHT(@LS_COLUMN,2)
				
				SET @LI_PARENT_BUDGET_ITEM_ID=@LI_BUDGET_ITEM_ID
				
				WHILE @LI_PARENT_BUDGET_ITEM_ID>0 AND NOT @LI_PARENT_BUDGET_ITEM_ID IS NULL
				BEGIN
					
					IF EXISTS(SELECT * FROM T_BUDGET_FORM_DETAIL WITH(NOLOCK) WHERE FID=@LI_BUDGET_FORM_ID AND FBUDGET_ITEM_ID=@LI_PARENT_BUDGET_ITEM_ID)
					BEGIN
						IF NOT @LI_PARENT_BUDGET_ITEM_ID=@LI_BUDGET_ITEM_ID
						BEGIN
							UPDATE T_BUDGET_FORM_VALUE SET FVALUE=ISNULL(FVALUE,0)+@LD_VALUE
							WHERE FID=@LI_BUDGET_FORM_ID AND FBUDGET_ITEM_ID=@LI_PARENT_BUDGET_ITEM_ID AND FCOLUMN=@LS_COLUMN
						END
						
						IF @LS_TIME IN ('S','M')
						BEGIN
							SET @LS_NAME=LEFT(@LS_COLUMN,1)+'Y000000'+SUBSTRING(@LS_COLUMN,9,4)+'00'
							
							UPDATE T_BUDGET_FORM_VALUE SET FVALUE=ISNULL(FVALUE,0)+@LD_VALUE
							WHERE FID=@LI_BUDGET_FORM_ID AND FBUDGET_ITEM_ID=@LI_PARENT_BUDGET_ITEM_ID AND FCOLUMN=@LS_NAME
						END
						
						IF @LS_TIME='M'
						BEGIN
							IF @LS_MONTH IN ('01','02','03')
							BEGIN
								SET @LS_NAME=LEFT(@LS_COLUMN,1)+'S000000'+SUBSTRING(@LS_COLUMN,9,4)+'01'
							END
							IF @LS_MONTH IN ('04','05','06')
							BEGIN
								SET @LS_NAME=LEFT(@LS_COLUMN,1)+'S000000'+SUBSTRING(@LS_COLUMN,9,4)+'02'
							END
							IF @LS_MONTH IN ('07','08','09')
							BEGIN
								SET @LS_NAME=LEFT(@LS_COLUMN,1)+'S000000'+SUBSTRING(@LS_COLUMN,9,4)+'03'
							END
							IF @LS_MONTH IN ('10','11','12')
							BEGIN
								SET @LS_NAME=LEFT(@LS_COLUMN,1)+'S000000'+SUBSTRING(@LS_COLUMN,9,4)+'04'
							END
							
							UPDATE T_BUDGET_FORM_VALUE SET FVALUE=ISNULL(FVALUE,0)+@LD_VALUE
							WHERE FID=@LI_BUDGET_FORM_ID AND FBUDGET_ITEM_ID=@LI_PARENT_BUDGET_ITEM_ID AND FCOLUMN=@LS_NAME
						END
					END
					
					SET @LI_PARENT_BUDGET_ITEM_ID=(SELECT FPARENT_ID FROM T_BUDGET_ITEM WITH(NOLOCK) WHERE FID=@LI_PARENT_BUDGET_ITEM_ID)
				END
				
				FETCH NEXT FROM LDS_FORM_VALUE
				INTO @LS_COLUMN,@LD_VALUE
				
			END
			
			CLOSE LDS_FORM_VALUE
			DEALLOCATE LDS_FORM_VALUE
			
			FETCH NEXT FROM LDS_FORM_DETAIL
			INTO @LI_BUDGET_ITEM_ID,@LI_VALUE_TYPE,@LI_TIME,@LS_VALUE_FORMULA_ORIGINAL,@LI_COLUMN
		END
		
		CLOSE LDS_FORM_DETAIL
		DEALLOCATE LDS_FORM_DETAIL
		
		FETCH NEXT FROM LDS_FORM_HEADER
		INTO @LI_BUDGET_MODEL_ID,@LS_BUDGET_MODEL_NO,@LS_BUDGET_MODEL_NAME,
		@LI_BUDGET_CENTER_ID,@LS_BUDGET_CENTER_NO,@LS_BUDGET_CENTER_NAME,
		@LD_START_DATE,@LD_END_DATE,@LI_YEAR_TARGET,@LD_YEAR_TARGET_START_DATE,@LD_YEAR_TARGET_END_DATE
	END
	
	CLOSE LDS_FORM_HEADER
	DEALLOCATE LDS_FORM_HEADER
	
	SET @LS_BUDGET_CASE_ID=RIGHT(@LS_BUDGET_CASE_ID,LEN(@LS_BUDGET_CASE_ID) -CHARINDEX(',',@LS_BUDGET_CASE_ID))
END

UPDATE T_TABLEID SET FCURRID=(SELECT MAX(H.FID) FROM T_BUDGET_FORM_HEADER AS H WITH(NOLOCK))
WHERE FTABLE='T_BUDGET_FORM_HEADER'

END
